// oxlint-disable max-lines

import type { IconSet } from '../types.js'

export const catppuccin: IconSet = {
  collect: 'catppuccin',
  folderExpandedSuffix: '-open',
  folderPrefix: 'folder-',
  defaults: { file: 'file', folder: 'folder' },
  fileStems: {
    'alex': [{ name: '.alexrc', extensions: ['', 'js', 'yaml', 'yml'] }],
    'astro-config': [
      { name: 'astro.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'babel': [
      { name: '.babel-plugin-macrosrc', extensions: ['', 'js', 'json', 'yaml', 'yml'] },
      { name: '.babelrc', extensions: ['', 'cjs', 'js', 'json', 'mjs'] },
      { name: 'babel.config', extensions: ['cjs', 'js', 'json', 'mjs'] },
    ],
    'benchmark': [
      { name: 'benchmark', extensions: ['md', 'rst', 'txt'] },
      { name: 'benchmarks', extensions: ['md', 'rst', 'txt'] },
    ],
    'changelog': [
      { name: 'changelog', extensions: ['md', 'rst', 'txt'], exact: false },
      { name: 'changes', extensions: ['', 'md', 'rst', 'txt'] },
    ],
    'commitlint': [
      { name: '.commitlint', extensions: ['yaml', 'yml'] },
      { name: '.commitlintrc', extensions: ['', 'cjs', 'cts', 'js', 'json', 'ts', 'yaml', 'yml'] },
      { name: 'commitlint.config', extensions: ['cjs', 'cts', 'js', 'ts'] },
    ],
    'contributing': [{ name: 'contributing', extensions: ['md', 'rst', 'txt'], exact: false }],
    'cspell': [
      { name: '.cspell', extensions: ['json', 'yaml', 'yml'] },
      { name: 'cspell.config', extensions: ['cjs', 'js', 'yaml', 'yml'] },
      { name: 'cspell', extensions: ['json', 'yaml', 'yml'] },
    ],
    'cypress': [{ name: 'cypress.config', extensions: ['cjs', 'js', 'mjs', 'ts'] }],
    'docker': [
      { name: 'containerfile', extensions: '*' },
      { name: 'dockerfile', extensions: '*' },
    ],
    'docker-compose': [
      { name: 'compose', extensions: ['yaml', 'yml'], exact: false },
      { name: 'docker-compose', extensions: ['yaml', 'yml'], exact: false },
    ],
    'docusaurus': [{ name: 'docusaurus.config', extensions: ['cjs', 'js', 'mjs', 'ts'] }],
    'env': [{ name: '.env', extensions: '*' }],
    'esbuild': [
      { name: 'esbuild', extensions: ['cjs', 'js', 'mjs', 'ts'] },
      { name: 'esbuild.config', extensions: ['cjs', 'js', 'mjs', 'ts'] },
    ],
    'eslint': [
      { name: '.eslintrc', extensions: ['', 'cjs', 'js', 'json', 'yaml', 'yml'] },
      { name: 'eslint.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'gatsby': [
      { name: 'gatsby-browser', extensions: ['js', 'tsx'] },
      { name: 'gatsby-config', extensions: ['js', 'mjs', 'ts'] },
      { name: 'gatsby-node', extensions: ['js', 'mjs', 'ts'] },
      { name: 'gatsby-ssr', extensions: ['js', 'tsx'] },
    ],
    'graphql': [
      { name: '.graphqlrc', extensions: ['', 'cjs', 'js', 'json', 'toml', 'ts', 'yaml', 'yml'] },
      { name: 'graphql.config', extensions: ['cjs', 'js', 'json', 'toml', 'ts', 'yaml', 'yml'] },
    ],
    'gulp': [{ name: 'gulpfile', extensions: ['cts', 'js', 'mjs', 'mts', 'ts'] }],
    'husky': [{ name: '.huskyrc', extensions: ['', 'js', 'json', 'yaml', 'yml'] }],
    'jest': [
      { name: '.jestrc', extensions: ['', 'js', 'json'] },
      { name: 'jest-e2e.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'jest-preset', extensions: ['cjs', 'js', 'json', 'mjs'] },
      { name: 'jest.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'jest.e2e.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'jest.preset', extensions: ['cjs', 'js', 'json', 'mjs'] },
      { name: 'jest.setup', extensions: ['js', 'ts'] },
    ],
    'knip': [
      { name: 'knip.config', extensions: ['js', 'ts'] },
      { name: 'knip', extensions: ['js', 'json', 'jsonc', 'ts'] },
    ],
    'license': [
      { name: 'copying', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'copyright', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license', extensions: ['', 'md', 'rst', 'txt'] },
    ],
    'lint-staged': [
      {
        name: '.lintstagedrc',
        extensions: ['', 'cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts', 'yaml', 'yml'],
      },
      { name: 'lint-staged.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'msbuild': [{ name: 'directory.build', extensions: ['props', 'rsp', 'targets'] }],
    'panda-css': [{ name: 'panda.config', extensions: ['cjs', 'js', 'mjs', 'mts', 'ts'] }],
    'playwright': [
      { name: 'playwright-ct.config', extensions: ['js', 'mjs', 'ts'] },
      { name: 'playwright', extensions: ['js', 'mjs', 'ts'], exact: false },
    ],
    'plop': [{ name: 'plopfile', extensions: ['cjs', 'js', 'mjs', 'ts'] }],
    'postcss': [
      { name: '.postcssrc', extensions: ['', 'cjs', 'cts', 'js', 'json', 'ts', 'yaml', 'yml'] },
      { name: 'postcss.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'prettier': [
      {
        name: '.prettierrc',
        extensions: [
          '',
          'cjs',
          'cts',
          'js',
          'json',
          'json5',
          'mjs',
          'mts',
          'toml',
          'ts',
          'yaml',
          'yml',
        ],
      },
      { name: 'prettier.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'prisma': [{ name: 'prisma.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'pug': [{ name: '.pug-lintrc', extensions: ['', 'js', 'json'] }],
    'puppeteer': [
      { name: '.puppeteerrc', extensions: ['', 'cjs', 'js', 'json', 'yaml'] },
      { name: 'puppeteer.config', extensions: ['cjs', 'js'] },
    ],
    'rollup': [
      { name: 'rollup-config', extensions: ['js', 'mjs', 'ts'] },
      { name: 'rollup.config', extensions: ['js', 'mjs', 'ts'], exact: false },
    ],
    'semantic-release': [
      { name: '.releaserc', extensions: ['', 'cjs', 'js', 'json', 'yaml', 'yml'] },
      { name: 'release.config', extensions: ['cjs', 'js'] },
    ],
    'serverless': [{ name: 'serverless', extensions: ['js', 'json', 'ts', 'yaml', 'yml'] }],
    'snowpack': [
      { name: 'snowpack.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
    ],
    'stylelint': [
      {
        name: '.stylelintrc',
        extensions: ['', 'cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts', 'yaml', 'yml'],
      },
      { name: 'stylelint.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'svelte-config': [{ name: 'svelte.config', extensions: ['cjs', 'js', 'mjs', 'ts'] }],
    'tailwind': [
      { name: 'tailwind.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'tailwind', extensions: ['js', 'ts'] },
    ],
    'typescript-config': [{ name: 'tsconfig', extensions: ['json'], exact: false }],
    'unocss': [
      { name: 'uno.config', extensions: ['js', 'mjs', 'mts', 'ts'] },
      { name: 'unocss.config', extensions: ['js', 'mjs', 'mts', 'ts'] },
    ],
    'vite': [{ name: 'vite.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'vitest': [
      { name: 'vitest.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'vitest.workspace', extensions: ['js', 'json', 'ts'] },
    ],
    'vue-config': [{ name: 'vue.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'webpack': [
      { name: 'webpack', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'], exact: false },
    ],
    'windi': [{ name: 'windi.config', extensions: ['cjs', 'cts', 'js', 'json', 'ts'] }],
  },
  fileNames: {
    'adonis': ['.adonisrc.json', 'ace'],
    'android': ['androidmanifest.xml'],
    'angular': ['.angular-cli.json', 'angular-cli.json', 'angular.json', 'ng-package.json'],
    'ansible-lint': ['.ansible-lint', 'ansible-lint.yaml', 'ansible-lint.yml'],
    'apache': ['jvm.config', 'maven.config', 'pom.xml'],
    'apollo': ['apollo.config.js', 'apollo.config.ts'],
    'apple': ['apple-app-site-association', 'apple-developer-merchantid-domain-association'],
    'azure-pipelines': [
      'azure-pipelines-main.yaml',
      'azure-pipelines-main.yml',
      'azure-pipelines.yaml',
      'azure-pipelines.yml',
    ],
    'babel': ['babel-plugin-macros.config.js', 'babel-transform.js'],
    'bash': [
      'applypatch-msg',
      'commit-msg',
      'post-applypatch',
      'post-checkout',
      'post-commit',
      'post-merge',
      'post-receive',
      'post-rewrite',
      'post-update',
      'pre-applypatch',
      'pre-auto-gc',
      'pre-commit',
      'pre-push',
      'pre-rebase',
      'pre-receive',
      'prepare-commit-message',
      'update',
    ],
    'bazel': ['.bazelrc'],
    'bicep': ['bicepconfig.json'],
    'biome': ['biome.json', 'biome.jsonc'],
    'bitbucket': ['bitbucket-pipelines.yaml', 'bitbucket-pipelines.yml'],
    'blitz': ['.blitz.config.compiled.js', 'blitz.config.js', 'blitz.config.ts'],
    'bower': ['.bowerrc', 'bower.json'],
    'browserslist': ['.browserslistrc', 'browserslist'],
    'bun': ['bun', 'bunfig.toml'],
    'bun-lock': ['bun.lock', 'bun.lockb'],
    'cabal': ['cabal.project'],
    'caddy': ['caddyfile'],
    'capacitor': ['capacitor.config.json', 'capacitor.config.ts'],
    'cargo': ['cargo.toml'],
    'cargo-lock': ['cargo.lock'],
    'changelog': ['changelog'],
    'circle-ci': ['circle.yml'],
    'cmake': ['cmakecache.txt', 'cmakelists.txt'],
    'code-climate': ['.codeclimate.yml'],
    'code-of-conduct': ['code_of_conduct', 'code_of_conduct.md', 'code_of_conduct.txt'],
    'codeowners': ['codeowners', 'owners'],
    'contributing': ['contributing'],
    'cursor': ['.cursorrules'],
    'cursor-ignore': ['.cursorignore', '.cursorindexingignore'],
    'cypress': ['cypress.env.json', 'cypress.json'],
    'deno': ['deno', 'deno.json', 'deno.jsonc'],
    'deno-lock': ['deno.lock'],
    'dependabot': ['dependabot.yaml', 'dependabot.yml'],
    'devcontainer': ['.devcontainer.json', 'devcontainer.json'],
    'drizzle-orm': ['drizzle.config.js', 'drizzle.config.ts'],
    'dub': ['dub.json', 'dub.sdl'],
    'dub-selections': ['dub.selections.json'],
    'editorconfig': ['.editorconfig'],
    'eleventy': [
      '.eleventy.js',
      '.eleventyignore',
      'eleventy.config.cjs',
      'eleventy.config.js',
      'eleventy.config.mjs',
    ],
    'ember': ['.ember-cli', '.ember-cli.js', 'ember-cli-builds.js'],
    'envrc': ['.envrc'],
    'eslint': ['.eslintrc-jsdoc.js', '.eslintrc-md.js'],
    'eslint-ignore': ['.eslintcache,', '.eslintignore'],
    'fastlane': [
      'appfile',
      'deliverfile',
      'fastfile',
      'gymfile',
      'matchfile',
      'scanfile',
      'snapfile',
    ],
    'favicon': ['favicon.ico'],
    'firebase': [
      '.firebaserc',
      'firebase.json',
      'firestore.indexes.json',
      'firestore.rules',
      'storage.rules',
    ],
    'flutter': ['.flutter-plugins', '.flutter-plugins-dependencies', '.metadata'],
    'foreman': ['aftman.toml', 'foreman.toml'],
    'fvm': ['.fvmrc', 'fvm_config.json'],
    'gcp': ['.release-please-manifest.json', 'release-please-config.json'],
    'git': [
      '.git',
      '.git-blame-ignore',
      '.git-blame-ignore-revs',
      '.git-for-windows-updater',
      '.gitattributes',
      '.gitattributes-global',
      '.gitattributes_global',
      '.gitconfig',
      '.gitignore',
      '.gitignore-global',
      '.gitignore_global',
      '.gitinclude',
      '.gitkeep',
      '.gitmessage',
      '.gitmodules',
      '.gitpreserve',
      '.keep',
      'git-history',
    ],
    'git-cliff': ['cliff.toml'],
    'gitpod': ['.gitpod.yml'],
    'gleam-config': ['gleam.toml'],
    'go-mod': ['go.mod', 'go.sum', 'go.work', 'go.work.sum'],
    'godot-assets': ['._sc_', '.gdignore', '_sc_'],
    'gradle': ['gradle-wrapper.properties', 'gradle.properties', 'gradlew'],
    'graphql': ['.graphqlconfig'],
    'hacking': ['hacking', 'hacking.md', 'hacking.txt'],
    'hardhat': ['hardhat.config.js', 'hardhat.config.ts'],
    'helm': ['.helmignore', 'chart.lock'],
    'heroku': ['procfile'],
    'histoire': ['.histoire.js', '.histoire.ts', 'histoire.config.js', 'histoire.config.ts'],
    'http': ['cname'],
    'hugo': ['hugo.json', 'hugo.toml', 'hugo.yaml'],
    'humans': ['humans.txt'],
    'husky': ['husky.config.js'],
    'ionic': ['.io-config.json', 'ionic.config.json'],
    'javascript-config': ['jsconfig.json'],
    'jest': [
      'jest-e2e.json',
      'jest-github-actions-reporter.js',
      'jest-unit.config.js',
      'jest.e2e.json',
      'jest.json',
      'jest.teardown.js',
    ],
    'json': [
      '.esformatter',
      '.jsbeautifyrc',
      '.jscsrc',
      '.jshintrc',
      '.whitesource',
      'cdp.pid',
      'composer.lock',
    ],
    'jule': ['jule.mod'],
    'just': ['.justfile', 'justfile'],
    'key': ['.htpasswd'],
    'knip': ['.knip.jsonc'],
    'laravel': ['artisan'],
    'lerna': ['lerna.json'],
    'license': [
      'licence-agpl',
      'licence-apache',
      'licence-bsd',
      'licence-gpl',
      'licence-lgpl',
      'licence-mit',
      'license-agpl',
      'license-apache',
      'license-bsd',
      'license-gpl',
      'license-lgpl',
      'license-mit',
      'unlicence',
      'unlicense',
    ],
    'liquid': ['.liquidrc', '.liquidrc.json'],
    'lua': ['.luacheckrc'],
    'lua-rocks': ['.rock', '.rockspec'],
    'luau-check': ['selene.toml', 'selene.yaml', 'selene.yml'],
    'luau-config': ['.luaurc'],
    'macos': ['.ds_store'],
    'makefile': ['gnumakefile', 'kbuild', 'makefile'],
    'mantle': ['.mantle-state.yml', 'mantle.yml'],
    'mdbook': ['book.toml'],
    'meson': ['meson.build', 'meson_options.txt'],
    'mjml': ['.mjmlconfig'],
    'modernizr': ['.modernizrrc', '.modernizrrc.js', '.modernizrrc.json'],
    'moonrepo': ['moon.yaml', 'moon.yml'],
    'moonwave': ['moonwave.toml'],
    'msbuild': ['directory.packages.props'],
    'nativescript': ['nativescript.config.js', 'nativescript.config.ts'],
    'nest': ['.nest-cli.json', '.nestconfig.json', 'nest-cli.json', 'nestconfig.json'],
    'netlify': ['netlify.json', 'netlify.toml', 'netlify.yaml', 'netlify.yml'],
    'next': ['next.config.js', 'next.config.mjs', 'next.config.mts', 'next.config.ts'],
    'nginx': ['nginx.conf'],
    'nix-lock': ['flake.lock'],
    'nodemon': ['nodemon-debug.json', 'nodemon.json'],
    'npm': ['.npmrc', 'npm'],
    'npm-ignore': ['.npmignore'],
    'npm-lock': ['package-lock.json'],
    'nuget': ['.nuspec', 'nuget.config', 'nuget.exe'],
    'nuxt': ['.nuxtrc', 'nuxt.config.js', 'nuxt.config.ts'],
    'nuxt-ignore': ['.nuxtignore'],
    'nx': ['nx.json'],
    'nx-ignore': ['.nxignore'],
    'package-json': ['.esmrc', '.node-version', '.nvmrc', 'package.json'],
    'pesde': ['pesde.toml'],
    'pesde-lock': ['pesde.lock'],
    'phrase': ['.phrase.yaml', '.phrase.yml', '.phraseapp.yaml', '.phraseapp.yml'],
    'pixi': ['pixi.toml'],
    'pixi-lock': ['pixi.lock'],
    'pnpm': ['.pnpmfile.cjs', 'pnpm', 'pnpm-workspace.yaml'],
    'pnpm-lock': ['pnpm-lock.yaml'],
    'poetry-lock': ['poetry.lock'],
    'pre-commit': ['.pre-commit-config.yaml', '.pre-commit-hooks.yaml'],
    'premake': ['premake.lua', 'premake4.lua', 'premake5.lua'],
    'prettier-ignore': ['.prettierignore'],
    'prisma': ['prisma.yml'],
    'prototools': ['.prototools'],
    'python-config': [
      '.python-version',
      'pyproject.toml',
      'requirements-dev.txt',
      'requirements-test.txt',
      'requirements.txt',
    ],
    'r': ['.rhistory'],
    'readme': ['readme', 'readme.md', 'readme.rst', 'readme.txt'],
    'redwood': ['redwood.toml'],
    'release': ['.goreleaser.yaml'],
    'remix': ['remix.config.js', 'remix.config.ts'],
    'renovate': [
      '.renovaterc',
      '.renovaterc.json',
      'renovate-config.json',
      'renovate.json',
      'renovate.json5',
    ],
    'robots': ['robots.txt'],
    'rocket': ['rocket.toml'],
    'rokit': ['rokit.toml'],
    'ruby': ['.ruby-version'],
    'ruby-gem': ['gemfile'],
    'ruby-gem-lock': ['gemfile.lock'],
    'ruff': ['.ruff.toml', 'ruff.toml'],
    'rust-config': ['.rustfmt.toml', 'clippy.toml', 'rust-toolchain.toml', 'rustfmt.toml'],
    'security': ['security', 'security.md', 'security.txt'],
    'semgrep': ['semgrep.yml'],
    'semgrep-ignore': ['.semgrepignore'],
    'sentry': ['.sentryclirc'],
    'snowpack': ['snowpack.deps.json'],
    'sonar-cloud': ['.sonarcloud.properties', 'sonar-project.properties', 'sonarcloud.yaml'],
    'stackblitz': ['.stackblitzrc'],
    'stencil': ['stencil.config.js', 'stencil.config.ts'],
    'stitches': ['stitches.config.js', 'stitches.config.ts'],
    'stylelint-ignore': ['.stylelintcache', '.stylelintignore'],
    'stylua': ['stylua.toml'],
    'stylua-ignore': ['.styluaignore'],
    'swiftformat': ['.swiftformat'],
    'taskfile': [
      '.taskrc.yaml',
      '.taskrc.yml',
      'taskfile.dist.yaml',
      'taskfile.dist.yml',
      'taskfile.yaml',
      'taskfile.yml',
    ],
    'tauri': [
      'tauri.toml',
      'tauri.conf.json',
      'tauri.conf.json5',
      'tauri.config.json',
      'tauri.linux.conf.json',
      'tauri.macos.conf.json',
      'tauri.windows.conf.json',
    ],
    'tauri-ignore': ['.taurignore'],
    'todo': ['todo.md', 'todos.md'],
    'turbo': ['turbo.json'],
    'typst': ['typst.toml'],
    'uv': ['uv.lock'],
    'v': ['v.mod', 'vpkg.json'],
    'vercel': ['now.json', 'vercel.json'],
    'vercel-ignore': ['.nowignore', '.vercelignore'],
    'vscode-ignore': ['.vscodeignore'],
    'vue-config': ['.vuerc'],
    'wally': ['wally.lock', 'wally.toml'],
    'wrangler': ['wrangler.json', 'wrangler.jsonc', 'wrangler.toml'],
    'wxt': ['wxt.config.js', 'wxt.config.ts'],
    'xmake': ['xmake.lua'],
    'xml': ['.htaccess'],
    'yarn': [
      '.yarn-integrity',
      '.yarnclean',
      '.yarnrc',
      '.yarnrc.yaml',
      '.yarnrc.yml',
      'yarn',
      'yarn-error.log',
      'yarn.config.cjs',
    ],
    'yarn-lock': ['yarn.lock'],
  },
  fileExtensions: {
    '3d': ['fbx', 'glb', 'gltf', 'ma', 'mb', 'obj', 'prc', 'stl', 'u3d', 'usd'],
    'adobe-ae': ['aep'],
    'adobe-ai': ['ai'],
    'adobe-id': ['indb', 'indd', 'indl'],
    'adobe-ps': ['psd'],
    'adobe-xd': ['xd'],
    'amber': ['ab', 'amber'],
    'android': ['apk', 'dex', 'smali'],
    'angular': ['ng-template'],
    'antlr': ['g4'],
    'apache': ['thrift'],
    'api-blueprint': ['apib', 'apiblueprint'],
    'arduino': ['ino'],
    'asciidoc': ['adoc', 'asciidoc'],
    'assembly': [
      'a51',
      'aea',
      'agc',
      'ags',
      'argus',
      'asm',
      'binsource',
      'inc',
      'mitigus',
      'ms',
      'nasm',
      's',
    ],
    'astro': ['astro'],
    'audio': [
      'aac',
      'aiff',
      'alac',
      'flac',
      'm4a',
      'm4p',
      'mogg',
      'mp3',
      'oga',
      'opus',
      'wav',
      'wma',
      'wv',
    ],
    'autohotkey': ['ahk'],
    'azure-pipelines': [
      'azure-pipelines-main.yaml',
      'azure-pipelines-main.yml',
      'azure-pipelines.yaml',
      'azure-pipelines.yml',
    ],
    'bash': ['awk', 'bash', 'csh', 'fish', 'ksh', 'sh', 'tcsh', 'zsh'],
    'batch': ['bat', 'cmd'],
    'bazel': ['bazel', 'bzl'],
    'bicep': ['bicep', 'bicepparam'],
    'binary': ['bin'],
    'blink': ['blink'],
    'c': ['c', 'i', 'mi'],
    'c-header': ['h'],
    'cabal': ['cabal'],
    'caddy': ['caddyfile'],
    'certificate': ['cer', 'cert', 'crt', 'entitlements', 'pfx'],
    'clojure': ['clj', 'cljc', 'cljs'],
    'cmake': ['cmake'],
    'cobol': ['cbl', 'cob'],
    'coffeescript': ['coffee', 'cson', 'iced'],
    'cpp': ['c++', 'cc', 'cp', 'cpp', 'cxx', 'ii', 'mii'],
    'cpp-header': ['h++', 'hh', 'hp', 'hpp', 'hxx', 'inl', 'tcc'],
    'crystal': ['cr', 'ecr'],
    'csharp': ['cs', 'csharp', 'csx'],
    'css': ['css'],
    'css-map': ['css.map'],
    'csv': ['csv', 'psv', 'tsv'],
    'cucumber': ['feature', 'features'],
    'cuda': ['cu', 'cuh'],
    'cue': ['cue'],
    'd': ['d', 'di'],
    'darklua': ['darklua.json', 'darklua.json5'],
    'dart': ['dart'],
    'dart-generated': ['config.dart', 'freezed.dart', 'g.dart', 'gr.dart'],
    'database': [
      'accdb',
      'dat',
      'db3',
      'mdb',
      'pdb',
      'pgsql',
      'pkb',
      'pks',
      'plpgsql',
      'postgres',
      'psql',
      'sql',
      'sqlite',
      'sqlite3',
    ],
    'dhall': ['dhall', 'dhallb'],
    'django': ['djt'],
    'docker': ['containerfile', 'dockerfile'],
    'docker-compose': ['compose.yaml', 'compose.yml', 'docker-compose.yaml', 'docker-compose.yml'],
    'docker-ignore': ['containerignore', 'dockerignore'],
    'drawio': ['dio', 'drawio'],
    'ejs': ['ejs'],
    'elixir': ['eex', 'ex', 'exs', 'heex', 'leex'],
    'elm': ['elm'],
    'env': ['env'],
    'erlang': ['erl'],
    'exe': ['exe', 'msi'],
    'figma': ['fig'],
    'font': [
      'bmap',
      'eot',
      'fnt',
      'font',
      'fonts',
      'mrf',
      'ntf',
      'odttf',
      'otf',
      'sui',
      'suit',
      'ttc',
      'ttf',
      'woff',
      'woff2',
    ],
    'fortran': ['f', 'f03', 'f08', 'f77', 'f90', 'f95', 'for'],
    'fsharp': ['fs', 'fsi', 'fsx'],
    'git': ['patch'],
    'gitlab': ['gitlab-ci.yaml', 'gitlab-ci.yml'],
    'gleam': ['gleam'],
    'go': ['go'],
    'go-template': ['go.html', 'go.tmp', 'gohtml', 'gotmpl', 'templ', 'tmpl'],
    'godot': ['gd'],
    'godot-assets': [
      'gd.uid',
      'gdextension',
      'gdnlib',
      'gdns',
      'gdshader',
      'gdshaderinc',
      'godot',
      'tres',
      'tscn',
    ],
    'gradle': ['gradle'],
    'graphql': ['gql', 'graphql'],
    'groovy': ['groovy'],
    'haml': ['haml'],
    'handlebars': ['hbs', 'mustache'],
    'hare': ['ha'],
    'haskell': ['hs'],
    'haxe': ['hx'],
    'html': ['asp', 'htm', 'html', 'html_vm', 'xhtml'],
    'http': ['http', 'rest'],
    'huff': ['huff'],
    'image': [
      'afphoto',
      'ami',
      'apx',
      'ase',
      'aseprite',
      'avif',
      'bmp',
      'bpg',
      'brk',
      'clip',
      'cpt',
      'cur',
      'dds',
      'dng',
      'eps',
      'exr',
      'fpx',
      'gbr',
      'gif',
      'heic',
      'heif',
      'icns',
      'ico',
      'img',
      'jb2',
      'jbig2',
      'jfif',
      'jng',
      'jpeg',
      'jpg',
      'jxr',
      'kra',
      'mdp',
      'ora',
      'pbm',
      'pdn',
      'pgf',
      'pgm',
      'pic',
      'png',
      'pnm',
      'ppm',
      'psb',
      'raw',
      'reb',
      'sai',
      'tga',
      'tif',
      'tiff',
      'webp',
      'xcf',
    ],
    'java': ['java', 'jsp'],
    'java-class': ['class'],
    'java-jar': ['jar'],
    'javascript': ['cjs', 'esx', 'js', 'mjs'],
    'javascript-config': ['jsconfig.json'],
    'javascript-map': ['cjs.map', 'js.map', 'mjs.map'],
    'javascript-react': ['jsx'],
    'javascript-test': [
      'cy.js',
      'cy.jsx',
      'e2e-spec.cjs',
      'e2e-spec.js',
      'e2e-spec.mjs',
      'js.snap',
      'jsx.snap',
      'spec.cjs',
      'spec.js',
      'spec.jsx',
      'spec.mjs',
      'test.cjs',
      'test.js',
      'test.jsx',
      'test.mjs',
    ],
    'jinja': ['j2', 'jinja', 'jinja-html', 'jinja2'],
    'json': ['hjson', 'json', 'json5', 'jsonc', 'jsonl', 'ndjson', 'tsbuildinfo', 'webmanifest'],
    'json-schema': ['schema.json'],
    'juce': ['jucer'],
    'jule': ['jule'],
    'julia': ['jl'],
    'jupyter': ['ipynb'],
    'just': ['just'],
    'kdl': ['kdl'],
    'key': ['asc', 'gpg', 'key', 'keystore', 'passwd', 'pem', 'pub'],
    'kotlin': ['kt', 'kts'],
    'laravel': ['blade.php', 'inky.php'],
    'latex': ['dtx', 'ltx', 'sty', 'tex'],
    'latte': ['latte'],
    'less': ['less'],
    'lib': ['bib', 'lib'],
    'liquid': ['liquid'],
    'lisp': ['cl', 'fast', 'lisp', 'lsp'],
    'log': ['log'],
    'lua': ['lua'],
    'lua-client': ['client.lua'],
    'lua-server': ['server.lua'],
    'lua-test': ['spec.lua', 'test.lua'],
    'luau': ['luau'],
    'luau-client': ['client.luau'],
    'luau-server': ['server.luau'],
    'luau-test': ['spec.luau', 'test.luau'],
    'makefile': ['mk'],
    'markdown': ['markdown', 'md', 'rst'],
    'markdown-mdx': ['mdx'],
    'marko': ['marko'],
    'matlab': ['m', 'mat'],
    'mermaid': ['mermaid', 'mmd'],
    'meson': ['wrap'],
    'midi': ['mid', 'midi'],
    'mjml': ['mjml'],
    'ms-excel': ['ods', 'xls', 'xlsb', 'xlsm', 'xlsx', 'xlt', 'xltm', 'xltx'],
    'ms-powerpoint': [
      'odp',
      'potm',
      'potx',
      'ppa',
      'ppam',
      'pps',
      'ppsm',
      'ppsx',
      'ppt',
      'pptm',
      'pptx',
    ],
    'ms-word': ['doc', 'docm', 'docx', 'dot', 'dotm', 'dotx', 'odt', 'rtf'],
    'nextflow': ['nf'],
    'nginx': ['nginx', 'nginxconf', 'nginxconfig'],
    'nim': ['nim', 'nimble'],
    'ninja': ['ninja'],
    'nix': ['nix'],
    'nuget': ['nupkg'],
    'nunjucks': ['njk', 'nunjucks'],
    'ocaml': ['cmx', 'ml', 'mli'],
    'odin': ['odin'],
    'opentofu': ['tofu', 'tofu.json'],
    'org': ['org'],
    'pdf': ['pdf'],
    'perl': [
      'nqp',
      'p6',
      'pl',
      'pl6',
      'pm',
      'pm6',
      'pod',
      'psgi',
      'raku',
      'rakudoc',
      'rakumod',
      'rakutest',
      't',
    ],
    'php': ['php'],
    'phtml': ['phtml'],
    'plantuml': ['plantuml', 'pu', 'puml'],
    'postcss': ['pcss', 'sss'],
    'powershell': ['ps1', 'ps1xml', 'psc1', 'psd1', 'psm1', 'pssc'],
    'prisma': ['prisma'],
    'prolog': ['p', 'pro'],
    'properties': [
      'cfg',
      'conf',
      'config',
      'dlc',
      'ini',
      'option',
      'prefs',
      'prop',
      'properties',
      'props',
      'settings',
      'sln.dotsettings',
      'sln.dotsettings.user',
    ],
    'proto': ['proto'],
    'pug': ['jade', 'pug'],
    'puppet': ['epp', 'pp'],
    'python': ['py'],
    'python-compiled': ['pyc', 'pyd', 'pyo'],
    'r': ['r'],
    'racket': ['rkt'],
    'razor': ['cshtml', 'vbhtml'],
    'rdata': ['rdata'],
    'reason': ['re', 'rei'],
    'rescript': ['res'],
    'rmd': ['rmd'],
    'roblox': ['rbxl', 'rbxlx', 'rbxm', 'rbxmx'],
    'rproj': ['rproj'],
    'rsml': ['rsml'],
    'ruby': ['erb', 'rb', 'rbs'],
    'rust': ['ron', 'rs'],
    'salesforce': ['cls'],
    'sass': ['sass', 'scss'],
    'scala': ['scala'],
    'scheme': ['scm'],
    'search': ['code-search'],
    'shader': [
      'comp',
      'comp.glsl',
      'comp.hlsl',
      'compute.glsl',
      'compute.hlsl',
      'computeshader',
      'frag',
      'frag.glsl',
      'fragment.glsl',
      'fragmentshader',
      'fs.glsl',
      'geom',
      'geom.glsl',
      'geom.hlsl',
      'geometry.glsl',
      'geometry.hlsl',
      'geometryshader',
      'glsl',
      'gs.glsl',
      'hlsl',
      'pixel.hlsl',
      'px.hlsl',
      'shader',
      'tesc',
      'tesc.glsl',
      'tese',
      'tese.glsl',
      'tess.hlsl',
      'tessellation.hlsl',
      'ts.glsl',
      'vert',
      'vert.glsl',
      'vertex.glsl',
      'vertexshader',
      'vs.glsl',
      'wgsl',
    ],
    'sketch': ['sketch'],
    'slidesk': ['sdf', 'sdt'],
    'solidity': ['sol'],
    'spwn': ['spwn'],
    'squirrel': ['nut'],
    'stata': ['ado', 'do', 'dta'],
    'storybook': [
      'stories.js',
      'stories.jsx',
      'stories.mdx',
      'stories.ts',
      'stories.tsx',
      'story.js',
      'story.jsx',
      'story.mdx',
      'story.ts',
      'story.tsx',
    ],
    'storybook-svelte': ['stories.svelte', 'story.svelte'],
    'storybook-vue': ['stories.vue', 'story.vue'],
    'sublime': ['sublime-project', 'sublime-workspace'],
    'super-collider': ['sc', 'scd'],
    'svelte': ['svelte'],
    'svg': ['svg'],
    'swift': ['swift'],
    'tauri': ['tauri'],
    'terraform': ['tf', 'tf.json', 'tfbackend', 'tfstate', 'tfvars'],
    'text': ['txt'],
    'todo': ['todo'],
    'toml': ['toml'],
    'twig': ['twig'],
    'twine': ['tw', 'twee'],
    'typescript': ['cts', 'mts', 'ts'],
    'typescript-config': ['tsconfig.json'],
    'typescript-def': ['d.cts', 'd.mts', 'd.ts'],
    'typescript-react': ['tsx'],
    'typescript-test': [
      'cy.ts',
      'cy.tsx',
      'e2e-spec.cts',
      'e2e-spec.mts',
      'e2e-spec.ts',
      'spec-d.ts',
      'spec.cts',
      'spec.mts',
      'spec.ts',
      'spec.tsx',
      'test-d.ts',
      'test.cts',
      'test.mts',
      'test.ts',
      'test.tsx',
      'ts.snap',
      'tsx.snap',
    ],
    'typst': ['typ'],
    'unity': ['unity'],
    'url': ['url'],
    'v': ['v'],
    'vala': ['vala'],
    'vanilla-extract': ['css.ts'],
    'vapi': ['vapi'],
    'vento': ['vto'],
    'verilog': ['sv', 'svh', 'vhd'],
    'vhs': ['tape'],
    'video': [
      'avi',
      'flv',
      'gifv',
      'm2v',
      'm4v',
      'mkv',
      'mov',
      'mp2',
      'mp4',
      'mpe',
      'mpeg',
      'mpg',
      'mpv',
      'ogg',
      'ogv',
      'qt',
      'rm',
      'rmvb',
      'vob',
      'webm',
      'wmv',
      'yuv',
    ],
    'vim': ['exrc', 'gvimrc', 'vim', 'viminfo', 'vimrc'],
    'visual-studio': [
      'csproj',
      'csproj.user',
      'fsproj',
      'fsproj.user',
      'ruleset',
      'sln',
      'slnf',
      'slnx',
      'suo',
      'vb',
      'vbproj',
      'vbproj.user',
      'vbs',
      'vcxitems',
      'vcxitems.filters',
      'vcxproj',
      'vcxproj.filters',
    ],
    'vital': ['vital', 'vitalbank', 'vitallfo', 'vitalskin', 'vitaltable', 'vitaltheme'],
    'vscode': [
      'code-profile',
      'code-snippets',
      'code-workplace',
      'code-workspace',
      'vsix',
      'vsixmanifest',
    ],
    'vue': ['vue'],
    'web-assembly': ['wasm', 'wat'],
    'windi': ['windi'],
    'workflow': ['workflows/yaml', 'workflows/yml'],
    'xaml': ['axaml', 'xaml'],
    'xcode': ['xcsettings', 'xcworkspacedata'],
    'xml': [
      'dmn',
      'dtd',
      'iml',
      'jrxml',
      'manifest',
      'plist',
      'project',
      'resx',
      'tmlanguage',
      'xml',
      'xml.dist',
      'xml.dist.sample',
      'xquery',
      'xsd',
      'xsl',
      'xslt',
    ],
    'yaml': ['yaml', 'yml'],
    'zap': ['zap'],
    'zig': ['zig'],
    'zip': [
      '7z',
      'arj',
      'aseprite-extension',
      'bz',
      'bz2',
      'db',
      'gz',
      'paq8n',
      'paq8o',
      'pkg',
      'rar',
      'tar',
      'tbz',
      'tbz2',
      'tgz',
      'xz',
      'z',
      'zip',
      'zpaq',
      'zst',
    ],
  },
  folderNames: {
    'admin': ['admin', 'admins', 'manager', 'managers', 'moderator', 'moderators'],
    'android': ['android'],
    'animation': ['anim', 'animated', 'animation', 'animations', 'anims'],
    'api': ['api', 'apis', 'restapi'],
    'app': ['app', 'apps'],
    'assets': ['asset', 'assets'],
    'audio': ['aud', 'audio', 'audios', 'auds', 'music', 'sound', 'sounds'],
    'audit': ['audit', 'audits'],
    'aws': ['.aws', 'aws'],
    'azure-devops': ['.azure-devops', '.azuredevops'],
    'azure-pipelines': ['.azure-pipelines'],
    'benchmark': [
      'bench',
      'benches',
      'benchmark',
      'benchmarks',
      'measure',
      'measurement',
      'measures',
      'performance',
    ],
    'caddy': ['.caddy', '.caddyfiles', 'caddy', 'caddyfiles'],
    'cargo': ['.cargo'],
    'circle-ci': ['.circleci'],
    'client': ['client', 'clients', 'frontend', 'frontends', 'pwa'],
    'cloud': ['cloud'],
    'command': ['cli', 'clis', 'cmd', 'command', 'commands'],
    'components': ['components', 'fragments', 'widget', 'widgets'],
    'composables': ['composable', 'composables'],
    'config': [
      '.config',
      '.setting',
      '.settings',
      'meta-inf',
      'cfg',
      'cfgs',
      'conf',
      'config',
      'configs',
      'configuration',
      'configurations',
      'confs',
      'option',
      'options',
      'setting',
      'settings',
    ],
    'connection': ['connection', 'connections', 'integration', 'integrations'],
    'constant': ['constant', 'constants'],
    'content': ['content', 'contents'],
    'controllers': [
      'controller',
      'controllers',
      'handler',
      'handlers',
      'provider',
      'providers',
      'service',
      'services',
    ],
    'core': ['core'],
    'coverage': [
      '.nyc-output',
      '.nyc_output',
      '__integration-test__',
      '__integration-tests__',
      'coverage',
      'e2e',
      'integration-test',
      'integration-tests',
      'it',
    ],
    'cursor': ['.cursor'],
    'cypress': ['.cypress', 'cypress'],
    'database': ['_data', 'data', 'database', 'databases', 'db', 'sql'],
    'debug': ['debug', 'debugging'],
    'devcontainer': ['.devcontainer'],
    'direnv': ['.direnv'],
    'dist': ['.output', 'bin', 'build', 'dist', 'dist-newstyle', 'out', 'release'],
    'docker': ['.docker', 'docker', 'dockerfiles'],
    'docs': [
      '_post',
      '_posts',
      'article',
      'articles',
      'doc',
      'docs',
      'document',
      'documentation',
      'documents',
      'post',
      'posts',
    ],
    'download': ['download', 'downloads'],
    'drizzle-orm': ['drizzle'],
    'examples': ['demo', 'demos', 'example', 'examples', 'sample', 'sample-data', 'samples'],
    'fastlane': ['.fastlane', 'fastlane'],
    'firebase': ['.firebase', 'firebase'],
    'fonts': ['font', 'fonts'],
    'forgejo': ['.forgejo'],
    'functions': [
      'calc',
      'calcs',
      'calculation',
      'calculations',
      'func',
      'funcs',
      'function',
      'functions',
      'lambda',
      'lambdas',
      'logic',
      'math',
      'maths',
    ],
    'fvm': ['.fvm'],
    'git': ['.git', '.githooks', '.submodules', 'githooks', 'patches', 'submodules'],
    'github': ['.github', 'github'],
    'gitlab': ['.gitlab'],
    'gradle': ['.gradle', 'gradle'],
    'graphql': ['gql', 'graphql'],
    'hooks': ['hook', 'hooks', 'trigger', 'triggers'],
    'husky': ['.husky', 'husky'],
    'images': [
      '_image',
      '_images',
      '_img',
      '_imgs',
      'fig',
      'figs',
      'figure',
      'figures',
      'ico',
      'icon',
      'icons',
      'icos',
      'image',
      'images',
      'img',
      'imgs',
      'photo',
      'photograph',
      'photographs',
      'photos',
      'pic',
      'pics',
      'picture',
      'pictures',
      'screengrab',
      'screengrabs',
      'screenshot',
      'screenshots',
    ],
    'include': ['include', 'includes'],
    'intellij': ['.idea'],
    'javascript': ['javascript', 'js'],
    'kubernetes': ['.k8s', '.kubernetes', 'k8s', 'kubernetes'],
    'layouts': ['_layouts', 'layout', 'layouts'],
    'lib': ['.lib', '.libraries', '.library', '.libs', 'lib', 'libraries', 'library', 'libs'],
    'linux': ['linux'],
    'locales': [
      '.tx',
      'i18n',
      'internationalization',
      'l10n',
      'lang',
      'langs',
      'language',
      'languages',
      'locale',
      'locales',
      'localization',
      'translate',
      'translation',
      'translations',
    ],
    'luau': ['luau_packages'],
    'lune': ['lune_packages'],
    'macos': ['mac', 'macos'],
    'messages': ['message', 'messages'],
    'middleware': ['middleware', 'middlewares'],
    'mocks': [
      '_draft',
      '_drafts',
      'concept',
      'concepts',
      'draft',
      'drafts',
      'fixture',
      'fixtures',
      'mock',
      'mocks',
      'sketch',
      'sketches',
    ],
    'moonrepo': ['.moon'],
    'next': ['.next'],
    'nix': ['nix'],
    'node': ['node_modules'],
    'nuxt': ['.nuxt', 'nuxt'],
    'packages': ['crate', 'crates', 'package', 'packages', 'pkg', 'pkgs'],
    'pesde': ['.pesde', 'pesde'],
    'plugins': [
      '_plugins',
      'addon',
      'addons',
      'extension',
      'extensions',
      'mod',
      'modding',
      'mods',
      'module',
      'modules',
      'plugin',
      'plugins',
    ],
    'pre-commit': ['pre-commit-channel'],
    'prisma': ['prisma'],
    'private': ['private'],
    'proto': ['proto', 'protobuf', 'protobufs', 'protos'],
    'public': [
      '_site',
      'browser',
      'browsers',
      'public',
      'site',
      'web',
      'website',
      'www',
      'wwwroot',
    ],
    'queue': ['bull', 'mq', 'queue', 'queues'],
    'redux': ['redux'],
    'renovate': ['.renovate', 'renovate'],
    'roblox': ['roblox_packages', 'roblox_server_packages'],
    'routes': ['router', 'routers', 'routes'],
    'sass': ['_sass', '_scss', 'sass', 'scss'],
    'scripts': ['script', 'scripting', 'scripts'],
    'security': ['security'],
    'server': ['backend', 'server', 'servers'],
    'shared': ['share', 'shared'],
    'src': ['code', 'source', 'sources', 'src', 'srcs'],
    'storybook': ['.storybook', '__stories__', 'stories', 'storybook'],
    'styles': ['css', 'style', 'styles', 'stylesheet', 'stylesheets'],
    'svg': ['svg', 'svgs'],
    'tauri': ['src-tauri'],
    'temp': ['.cache', '.temp', '.tmp', 'cache', 'cached', 'temp', 'tmp'],
    'templates': ['template', 'templates'],
    'tests': [
      '__fixtures__',
      '__mocks__',
      '__snapshots__',
      '__test__',
      '__tests__',
      'spec',
      'specs',
      'test',
      'testing',
      'tests',
    ],
    'themes': ['theme', 'themes'],
    'turbo': ['.turbo'],
    'types': ['@types', 'types', 'typings'],
    'upload': ['upload', 'uploads'],
    'utils': ['util', 'utilities', 'utility', 'utils'],
    'vercel': ['.now', '.vercel', 'now', 'vercel'],
    'video': ['movie', 'movies', 'vid', 'video', 'videos', 'vids'],
    'views': ['html', 'page', 'pages', 'public_html', 'screen', 'screens', 'view', 'views'],
    'vscode': ['.vscode', '.vscode-test'],
    'windows': ['windows'],
    'workflows': ['.ci', 'ci', 'workflow', 'workflows'],
    'wxt': ['.wxt'],
    'xcode': ['xcodeproj', 'xcschemes', 'xcshareddata', 'xcworkspace'],
    'xmake': ['.xmake', 'xmake'],
    'yarn': ['.yarn'],
  },
}
