// oxlint-disable max-lines

import type { IconSet } from '../types.js'

export const vscodeIcons: IconSet = {
  collect: 'vscode-icons',
  folderExpandedSuffix: '-opened',
  defaults: { file: 'default-file', folder: 'default-folder' },
  filePrefix: 'file-type-',
  folderPrefix: 'folder-type-',
  fileStems: {
    'allure': [{ name: '.allurerc', extensions: ['cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] }],
    'astroconfig': [{ name: 'astro.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'asyncapi': [{ name: 'asyncapi', extensions: ['json', 'yaml', 'yml'] }],
    'babel': [
      { name: '.babel-plugin-macrosrc', extensions: ['', 'js', 'json', 'yaml', 'yml'] },
      { name: '.babelrc', extensions: ['', 'cjs', 'js', 'json', 'mjs'] },
      { name: 'babel.config', extensions: ['cjs', 'js', 'json', 'mjs'] },
    ],
    'behat': [
      { name: 'behat', extensions: ['yaml', 'yml', 'php'] },
      { name: 'behat.dist', extensions: ['yaml', 'yml', 'php'] },
    ],
    'bundlemon': [
      { name: 'bundlemon.config', extensions: ['cjs', 'js', 'mjs'] },
      { name: '.bundlemonrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] },
    ],
    'capacitor': [{ name: 'capacitor.config', extensions: ['json', 'ts'] }],
    'changelogen': [{ name: 'changelog.config', extensions: ['cjs', 'js', 'json', 'mjs', 'ts'] }],
    'codegen': [
      { name: 'codegen', extensions: ['js', 'ts', 'json', 'yaml', 'yml'] },
      { name: '.codegenrc', extensions: ['', 'js', 'ts', 'json', 'yaml', 'yml'] },
    ],
    'commitlint': [
      { name: '.commitlint', extensions: ['', 'yaml', 'yml'] },
      { name: 'commitlint.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'ts'] },
      { name: '.commitlintrc', extensions: ['', 'cjs', 'cts', 'js', 'json', 'ts', 'yaml', 'yml'] },
    ],
    'craco': [
      { name: 'craco.config', extensions: ['cjs', 'js', 'ts'] },
      { name: '.cracorc', extensions: ['', 'js', 'ts'] },
    ],
    'cspell': [
      { name: '.cspell', extensions: ['json', 'jsonc', 'yaml', 'yml'] },
      {
        name: '.cspell.config',
        extensions: [
          'cjs',
          'cts',
          'js',
          'json',
          'jsonc',
          'mjs',
          'mts',
          'toml',
          'ts',
          'yaml',
          'yml',
        ],
      },
      { name: 'cspell', extensions: ['json', 'jsonc', 'yaml', 'yml'] },
      {
        name: 'cspell.config',
        extensions: [
          'cjs',
          'cts',
          'js',
          'json',
          'jsonc',
          'mjs',
          'mts',
          'toml',
          'ts',
          'yaml',
          'yml',
        ],
      },
    ],
    'cypress': [{ name: 'cypress.config', extensions: ['cjs', 'js', 'mjs', 'ts'] }],
    'deno': [{ name: 'deno', extensions: ['json', 'jsonc', 'lock'] }],
    'denoify': [{ name: 'denoify.config', extensions: ['js', 'json'] }],
    'devvit': [
      { name: 'devvit', extensions: ['json'] },
      { name: 'devvit.config', extensions: ['cjs', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'devvit.config.dev', extensions: ['cjs', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'devvit.config.prod', extensions: ['cjs', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'devvit.config.test', extensions: ['cjs', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'devvit.dev', extensions: ['json'] },
      { name: 'devvit.prod', extensions: ['json'] },
      { name: 'devvit.test', extensions: ['json'] },
    ],
    'docker': [
      { name: 'compose', extensions: ['yaml', 'yml'] },
      { name: 'docker-cloud', extensions: ['yaml', 'yml'] },
      { name: 'docker-compose', extensions: ['yaml', 'yml'], exact: false },
    ],
    'docusaurus': [
      { name: 'docusaurus.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'docz': [
      { name: '.docz', extensions: ['js', 'json'] },
      { name: 'docz', extensions: ['js', 'json'] },
      { name: 'docz.config', extensions: ['js', 'json'] },
      { name: 'doczrc', extensions: ['', 'js', 'json'] },
    ],
    'dotenv': [{ name: '.env', extensions: '*' }],
    'drawio': [
      { name: '.dio', extensions: ['png', 'svg'] },
      { name: '.drawio', extensions: ['png', 'svg'] },
    ],
    'drizzle-orm': [{ name: 'drizzle.config', extensions: ['js', 'json', 'ts'] }],
    'esbuild': [
      { name: 'esbuild', extensions: ['cjs', 'js', 'mjs', 'ts'] },
      { name: 'esbuild.config', extensions: ['cjs', 'js', 'mjs', 'ts'] },
    ],
    'eslint': [
      { name: 'eslint.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      {
        name: '.eslintrc',
        extensions: ['', 'cjs', 'cts', 'js', 'mjs', 'mts', 'ts', 'json', 'yaml', 'yml'],
      },
    ],
    'expo': [{ name: 'app.config', extensions: ['js', 'json', 'json5'] }],
    'flareact': [{ name: 'flareact.config', extensions: ['js'] }],
    'formkit': [
      { name: 'formkit.config', extensions: ['cjs', 'js', 'mjs', 'ts'] },
      { name: 'formkit.theme', extensions: ['cjs', 'js', 'mjs', 'ts'] },
    ],
    'gatsby': [
      { name: 'gatsby-browser', extensions: ['js', 'ts', 'tsx'] },
      { name: 'gatsby-config', extensions: ['js', 'mjs', 'ts'] },
      { name: 'gatsby-node', extensions: ['js', 'mjs', 'ts'] },
      { name: 'gatsby-ssr', extensions: ['js', 'ts', 'tsx'] },
    ],
    'gitpod': [
      { name: '.gitpod', extensions: ['yaml', 'yml'] },
      { name: 'gitpod', extensions: ['yaml', 'yml'] },
    ],
    'golangci': [{ name: '.golangci', extensions: ['json', 'toml', 'yaml', 'yml'] }],
    'graphql-config': [{ name: '.graphqlconfig', extensions: ['yaml', 'yml'] }],
    'gridsome': [
      { name: 'gridsome.client', extensions: ['js', 'ts'] },
      { name: 'gridsome.config', extensions: ['js', 'ts'] },
      { name: 'gridsome.server', extensions: ['js', 'ts'] },
    ],
    'grunt': [
      { name: 'gruntfile', extensions: ['cjs', 'coffee', 'js', 'ts'] },
      { name: 'gruntfile.babel', extensions: ['cjs', 'coffee', 'js', 'ts'] },
    ],
    'gulp': [
      { name: 'gulpfile', extensions: ['coffee', 'js', 'mjs', 'ts'] },
      { name: 'gulpfile.babel', extensions: ['coffee', 'js', 'mjs', 'ts'] },
      { name: 'gulpfile.esm', extensions: ['coffee', 'js', 'mjs', 'ts'] },
    ],
    'hardhat': [{ name: 'hardhat.config', extensions: ['cjs', 'js', 'ts'] }],
    'htmlvalidate': [{ name: '.htmlvalidate', extensions: ['cjs', 'js', 'json'] }],
    'husky': [{ name: '.huskyrc', extensions: ['', 'js', 'json', 'yaml', 'yml'] }],
    'jest': [
      { name: '.jestrc', extensions: ['', 'js', 'json'] },
      { name: 'jest-e2e.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'jest-preset', extensions: ['cjs', 'js', 'json', 'mjs'] },
      {
        name: 'jest.config',
        extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'],
        exact: false,
      },
      { name: 'jest.e2e.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'jest.preset', extensions: ['cjs', 'js', 'json', 'mjs'] },
      { name: 'jest.setup', extensions: ['js', 'ts'] },
    ],
    'jscpd': [{ name: 'jscpd-report', extensions: ['html', 'json', 'xml'] }],
    'karma': [{ name: 'karma.conf', extensions: ['coffee', 'js', 'ts'] }],
    'knex': [{ name: 'knexfile', extensions: ['coffee', 'eg', 'js', 'ls', 'ts'] }],
    'knip': [
      { name: 'knip.config', extensions: ['js', 'ts'] },
      { name: 'knip', extensions: ['js', 'json', 'jsonc', 'ts'] },
    ],
    'kysely': [{ name: 'kysely.config', extensions: ['ts', 'mts', 'cts', 'js', 'mjs', 'cjs'] }],
    'lefthook': [
      { name: '.lefthook', extensions: ['json', 'toml', 'yaml', 'yml'] },
      { name: '.lefthook-local', extensions: ['json', 'toml', 'yaml', 'yml'] },
      { name: 'lefthook', extensions: ['json', 'toml', 'yaml', 'yml'] },
      { name: 'lefthook-local', extensions: ['json', 'toml', 'yaml', 'yml'] },
    ],
    'license': [
      { name: 'copying', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'copyright', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'copying.lesser', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license-agpl', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license-bsd', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license-apache', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license-lgpl', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license-gpl', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'license-mit', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence-agpl', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence-bsd', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence-apache', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence-lgpl', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence-gpl', extensions: ['', 'md', 'rst', 'txt'] },
      { name: 'licence-mit', extensions: ['', 'md', 'rst', 'txt'] },
    ],
    'lighthouse': [{ name: '.lighthouserc', extensions: ['', 'cjs', 'js', 'json', 'yaml', 'yml'] }],
    'lintstagedrc': [
      {
        name: '.lintstagedrc',
        extensions: ['', 'cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts', 'yaml', 'yml'],
      },
      { name: 'lint-staged.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'markdownlint': [
      { name: '.markdownlint', extensions: ['cjs', 'json', 'jsonc', 'yaml', 'yml'] },
      { name: '.markdownlint-cli2', extensions: ['cjs', 'json', 'jsonc', 'yaml', 'yml'] },
    ],
    'markuplint': [
      { name: '.markuplintrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'ts', 'yaml', 'yml'] },
      { name: 'markuplint.config', extensions: ['cjs', 'js', 'json', 'mjs', 'ts', 'yaml', 'yml'] },
    ],
    'master-co': [
      { name: 'master', extensions: ['js', 'json', 'mjs', 'ts'] },
      { name: 'master.css', extensions: ['js', 'json', 'mjs', 'ts'] },
    ],
    'maven': [
      { name: 'extensions', extensions: ['xml'] },
      { name: 'pom', extensions: ['xml'] },
      { name: 'settings', extensions: ['xml'] },
    ],
    'mdx-components': [
      {
        name: 'mdx-components',
        extensions: ['cjs', 'cts', 'js', 'jsx', 'mjs', 'mts', 'ts', 'tsx'],
      },
    ],
    'mdxlint': [
      { name: '.mdxlintrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] },
    ],
    'metro': [
      { name: 'metro', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'metro.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
    ],
    'moniq': [{ name: 'moniq.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'mikro-orm': [{ name: 'mikro-orm.config', extensions: ['js', 'ts'] }],
    'mise': [
      { name: '.mise', extensions: ['toml'] },
      { name: '.mise.local', extensions: ['toml'] },
      { name: 'mise', extensions: ['toml'] },
      { name: 'mise.local', extensions: ['toml'] },
    ],
    'mocha': [
      { name: '.mocharc', extensions: ['', 'cjs', 'js', 'json', 'jsonc', 'mjs', 'yaml', 'yml'] },
    ],
    'modernizr': [
      { name: '.modernizr', extensions: ['js'] },
      { name: '.modernizrrc', extensions: ['', 'js'] },
      { name: 'modernizr', extensions: ['js'] },
      { name: 'modernizrrc', extensions: ['', 'js'] },
    ],
    'modernjs': [
      { name: 'modern.config', extensions: ['js', 'mjs', 'ts'] },
      { name: 'modern.runtime', extensions: ['js', 'mjs', 'ts'] },
      { name: 'modern.server', extensions: ['js', 'mjs', 'ts'] },
    ],
    'moleculer': [{ name: 'moleculer.config', extensions: ['js', 'json', 'ts'] }],
    'nanostaged': [{ name: 'nano-staged', extensions: ['cjs', 'js', 'json', 'mjs'] }],
    'nitro': [
      {
        name: 'nitro',
        extensions: [
          'js',
          'ts',
          'mjs',
          'cjs',
          'mts',
          'cts',
          'json',
          'jsonc',
          'json5',
          'yaml',
          'yml',
          'toml',
        ],
      },
      {
        name: 'nitro.config',
        extensions: [
          'js',
          'ts',
          'mjs',
          'cjs',
          'mts',
          'cts',
          'json',
          'jsonc',
          'json5',
          'yaml',
          'yml',
          'toml',
        ],
      },
    ],
    'npmpackagejsonlint': [
      { name: 'npmpackagejsonlint', extensions: ['cjs', 'js', 'mjs'] },
      { name: 'npmpackagejsonlintrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] },
    ],
    'nsri': [{ name: '.nsrirc', extensions: ['', 'js', 'json', 'yaml', 'yml'] }],
    'nuxt': [
      { name: 'nuxt', extensions: ['js', 'mjs', 'ts'] },
      { name: 'nuxt.config', extensions: ['js', 'mjs', 'ts'] },
    ],
    'orval': [{ name: 'orval.config', extensions: ['js', 'mjs', 'ts'] }],
    'oxc': [
      { name: 'oxfmt.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      { name: '.oxfmtrc', extensions: ['', 'json', 'jsonc'] },
      { name: 'oxlint.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      { name: '.oxlintrc', extensions: ['', 'json', 'jsonc'] },
    ],
    'packship': [
      { name: 'packship.config', extensions: ['js', 'json', 'mjs', 'mts', 'ts'] },
      { name: '.packshiprc', extensions: ['', 'js', 'json', 'ts'] },
    ],
    'paket': [
      { name: 'paket', extensions: ['dependencies', 'local', 'lock', 'references', 'template'] },
    ],
    'pandacss': [{ name: 'panda.config', extensions: ['js', 'mjs', 'ts'] }],
    'pdm': [{ name: 'pdm', extensions: ['lock', 'toml'] }],
    'phpstan': [
      { name: 'phpstan', extensions: ['neon'] },
      { name: 'phpstan.dist', extensions: ['neon'] },
    ],
    'playwright': [
      { name: 'playwright.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'pm2': [{ name: 'ecosystem.config', extensions: ['cjs', 'js', 'json', 'yaml', 'yml'] }],
    'poetry': [{ name: 'poetry', extensions: ['lock'] }],
    'postcssconfig': [
      { name: '.postcssrc', extensions: ['', 'cjs', 'cts', 'js', 'json', 'ts', 'yaml', 'yml'] },
      { name: 'postcss.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'preact': [{ name: 'preact.config', extensions: ['js'] }],
    'prettier': [
      {
        name: '.prettierrc',
        extensions: ['', 'cjs', 'js', 'json', 'json5', 'mjs', 'toml', 'yaml', 'yml'],
      },
      { name: 'prettier.config', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
    ],
    'prismaconfig': [{ name: 'prisma.config', extensions: ['js', 'ts'] }],
    'protractor': [{ name: 'protractor.conf', extensions: ['coffee', 'js', 'ts'] }],
    'pulumi': [
      { name: 'pulumi', extensions: ['yaml', 'yml'] },
      { name: 'pulumi.dev', extensions: ['yaml', 'yml'] },
      { name: 'pulumi.prod', extensions: ['yaml', 'yml'] },
    ],
    'quasar': [{ name: 'quasar.config', extensions: ['cjs', 'js', 'mjs', 'ts'] }],
    'razzle': [{ name: 'razzle.config', extensions: ['js'] }],
    'reactrouter': [{ name: 'react-router.config', extensions: ['js', 'ts'] }],
    'rehype': [{ name: '.rehyperc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] }],
    'remark': [{ name: '.remarkrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] }],
    'renovate': [{ name: 'renovate', extensions: ['json', 'json5'] }],
    'retext': [{ name: '.retextrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'yaml', 'yml'] }],
    'rolldown': [
      { name: 'rolldown.config', extensions: ['cjs', 'coffee', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      {
        name: 'rolldown.config.common',
        extensions: ['cjs', 'coffee', 'cts', 'js', 'mjs', 'mts', 'ts'],
      },
      {
        name: 'rolldown.config.dev',
        extensions: ['cjs', 'coffee', 'cts', 'js', 'mjs', 'mts', 'ts'],
      },
      {
        name: 'rolldown.config.prod',
        extensions: ['cjs', 'coffee', 'cts', 'js', 'mjs', 'mts', 'ts'],
      },
    ],
    'rollup': [
      { name: 'rollup.config', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'rollup.config.common', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'rollup.config.dev', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'rollup.config.prod', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
    ],
    'rspack': [
      { name: 'rstack.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rspack.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rsbuild.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rslib.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rspress.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rsdoctor.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rstest.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
      { name: 'rslint.config', extensions: ['js', 'ts', 'mjs', 'mts', 'cjs', 'cts'] },
    ],
    'seedkit': [{ name: 'seedkit.config', extensions: ['js', 'mjs', 'ts'] }],
    'semanticrelease': [{ name: 'release.config', extensions: ['js', 'cjs', 'ts', 'mjs'] }],
    'sequelize': [{ name: '.sequelizerc', extensions: ['', 'js', 'json'] }],
    'serverless': [{ name: 'serverless', extensions: ['js', 'json', 'ts', 'yml'] }],
    'slashup': [{ name: 'slash-up.config', extensions: ['js'] }],
    'sst': [
      { name: 'sst-env', extensions: ['d.ts', 'js', 'ts'] },
      { name: 'sst.config', extensions: ['d.ts', 'js', 'ts'] },
    ],
    'storybook': [
      { name: 'stories', extensions: ['js', 'jsx', 'mdx', 'svelte', 'ts', 'tsx'] },
      { name: 'story', extensions: ['js', 'jsx', 'mdx', 'svelte', 'ts', 'tsx'] },
    ],
    'stryker': [
      { name: '.stryker.conf', extensions: ['cjs', 'conf', 'js', 'json', 'mjs'] },
      { name: '.stryker.config', extensions: ['cjs', 'conf', 'js', 'json', 'mjs'] },
      { name: 'stryker-config', extensions: ['cjs', 'conf', 'js', 'json', 'mjs'] },
      { name: 'stryker.conf', extensions: ['cjs', 'conf', 'js', 'json', 'mjs'] },
      { name: 'stryker.config', extensions: ['cjs', 'conf', 'js', 'json', 'mjs'] },
      { name: 'stryker4s', extensions: ['cjs', 'conf', 'js', 'json', 'mjs'] },
    ],
    'stylelint': [
      { name: '.stylelintrc', extensions: ['', 'cjs', 'js', 'json', 'mjs', 'ts', 'yaml', 'yml'] },
      { name: 'stylelint.config', extensions: ['cjs', 'js', 'json', 'mjs', 'ts', 'yaml', 'yml'] },
    ],
    'svgo': [{ name: 'svgo.config', extensions: ['cjs', 'js', 'mjs'] }],
    'syncpack': [
      { name: '.syncpackrc', extensions: ['', 'cjs', 'js', 'mjs', 'ts'] },
      { name: 'syncpack.config', extensions: ['cjs', 'js', 'mjs', 'ts'] },
    ],
    'tailwind': [
      { name: '.tailwind', extensions: ['cjs', 'coffee', 'js', 'json', 'mjs', 'ts'] },
      { name: '.tailwindrc', extensions: ['', 'cjs', 'coffee', 'js', 'json', 'mjs', 'ts'] },
      { name: 'tailwind', extensions: ['cjs', 'coffee', 'js', 'json', 'mjs', 'ts'] },
      { name: 'tailwind.config', extensions: ['cjs', 'coffee', 'js', 'json', 'mjs', 'ts'] },
    ],
    'tamagui': [
      { name: 'tamagui', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'tamagui.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
    'taskfile': [
      { name: 'taskfile', extensions: ['yaml', 'yml'] },
      { name: 'taskfile.dist', extensions: ['yaml', 'yml'] },
    ],
    'testjs': [
      { name: 'spec', extensions: ['js', 'jsx', 'mjs', 'mts', 'ts', 'tsx'] },
      { name: 'test', extensions: ['js', 'jsx', 'mjs', 'mts', 'ts', 'tsx'] },
    ],
    'testplane': [
      { name: 'testplane.config', extensions: ['cjs', 'cts', 'js', 'ts'] },
      { name: 'testplane.conf', extensions: ['cjs', 'cts', 'js', 'ts'] },
    ],
    'testts': [
      { name: 'e2e-spec', extensions: ['mts', 'ts', 'tsx'] },
      { name: 'e2e-test', extensions: ['mts', 'ts', 'tsx'] },
      { name: 'test-d', extensions: ['mts', 'ts', 'tsx'] },
    ],
    'textlint': [{ name: '.textlintrc', extensions: ['', 'cjs', 'js', 'json', 'yaml', 'yml'] }],
    'truffle': [{ name: 'truffle-config', extensions: ['js', 'ts'] }],
    'tsconfig': [{ name: 'tsconfig', extensions: ['json'], exact: false }],
    'tsdown': [
      { name: 'tsdown.config', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
    ],
    'typedoc': [
      { name: 'typedoc', extensions: ['cjs', 'js', 'json', 'jsonc', 'mjs'] },
      { name: 'typedoc.config', extensions: ['cjs', 'js', 'json', 'jsonc', 'mjs'] },
    ],
    'unibeautify': [{ name: '.unibeautifyrc', extensions: ['', 'js', 'json', 'yaml', 'yml'] }],
    'unlicense': [
      { name: 'unlicence', extensions: ['md', 'txt'] },
      { name: 'unlicense', extensions: ['md', 'txt'] },
    ],
    'unocss': [
      { name: 'uno.config', extensions: ['js', 'mjs', 'mts', 'ts'] },
      { name: 'unocss.config', extensions: ['js', 'mjs', 'mts', 'ts'] },
    ],
    'vite': [{ name: 'vite.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'vitest': [
      { name: 'vitest.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
      { name: 'vitest.projects', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'vitest.workspace', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
    ],
    'vscode': [
      { name: 'launch', extensions: ['json'] },
      { name: 'tasks', extensions: ['json'] },
      { name: 'vscodeignore', extensions: ['json'] },
    ],
    'vscode-test': [{ name: '.vscode-test', extensions: ['js', 'json', 'mjs'] }],
    'wallaby': [
      { name: '.wallaby', extensions: ['coffee', 'js', 'json', 'ts'] },
      { name: '.wallaby.conf', extensions: ['coffee', 'js', 'json', 'ts'] },
      { name: 'wallaby', extensions: ['coffee', 'js', 'json', 'ts'] },
      { name: 'wallaby.conf', extensions: ['coffee', 'js', 'json', 'ts'] },
    ],
    'wdio': [
      { name: 'wdio', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
      { name: 'wdio.conf', extensions: ['cjs', 'cts', 'js', 'json', 'mjs', 'mts', 'ts'] },
    ],
    'webpack': [
      { name: 'webpack.base.conf', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.common', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.config', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'], exact: false },
      { name: 'webpack.conf', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'], exact: false },
      { name: 'webpack.dev', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.dev.conf', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.local', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.main.config', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.mix', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.plugins', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.prod', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.prod.conf', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.renderer.config', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.rules', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
      { name: 'webpack.test.conf', extensions: ['cjs', 'coffee', 'js', 'mjs', 'ts'] },
    ],
    'wxt': [{ name: 'wxt.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] }],
    'xo': [
      { name: '.xo-config', extensions: ['cjs', 'js', 'json'] },
      { name: 'xo.config', extensions: ['cjs', 'cts', 'js', 'mjs', 'mts', 'ts'] },
    ],
  },
  fileNames: {
    'agents': ['agents.md'],
    'aikido': ['.aikido'],
    'alchemy': ['alchemy.run.ts'],
    'allcontributors': ['.all-contributorsrc'],
    'angular': ['angular-cli.json', 'angular.json'],
    'antlers-html': ['antlers.html'],
    'api-extractor': ['api-extractor-base.json', 'api-extractor.json'],
    'appsemble': ['app-definition.yaml', '.appsemblerc.yaml'],
    'appveyor': ['appveyor.yml'],
    'assembly-script': ['asconfig.json'],
    'attw': ['attw.json'],
    'aurelia': ['aurelia.json'],
    'azurepipelines': ['azure-pipelines.yml', 'vsts-ci.yml'],
    'azureresourcemanager': [
      'azuredeploy.json',
      'azuredeploy.parameters.json',
      'azuredeploy.parameters.us.json',
      'createuidefinition.json',
    ],
    'babel': ['.babelignore'],
    'bazaar': ['.bzrignore'],
    'bazel': ['bazel.bazelrc', 'bazel.rc', '.bazelrc', 'build.bazel'],
    'bazel-ignore': ['.bazelignore'],
    'bazel-version': ['bazelversion'],
    'behat': ['behat.yaml.dist', 'behat.yml.dist'],
    'biome': ['biome.json', 'biome.jsonc'],
    'bitbucketpipeline': ['bitbucket-pipelines.yml'],
    'bithound': ['.bithoundrc'],
    'bower': ['bower.json', '.bowerrc'],
    'brakeman': ['brakeman.ignore', 'brakeman.yml'],
    'brew': ['brewfile'],
    'browserslist': ['browserslist', '.browserslistrc'],
    'buckbuild': ['buckconfig'],
    'bun': ['bun', 'bun-version', 'bun.lock', 'bun.lockb'],
    'bundler': ['gemfile', 'gemfile.lock'],
    'bunfig': ['bunfig.toml'],
    'caddy': ['caddyfile'],
    'cargo': ['cargo.lock', 'cargo.toml'],
    'changelogen': ['.changelogenrc', '.changelogrc'],
    'changie': ['changie.yaml', 'changie.yml'],
    'checkov': ['.checkov.yaml', '.checkov.yml'],
    'chef': ['berksfile', 'berksfile.lock', '.chefignore', 'policyfile.lock.json', 'policyfile.rb'],
    'circleci': ['.circle.yml'],
    'clangd': ['clangd'],
    'claude': ['claude.local.md', 'claude.md'],
    'cloudflare': ['wrangler.json', 'wrangler.jsonc', 'wrangler.toml'],
    'cloudfoundry': ['.cfignore'],
    'codacy': ['codacy.yaml', 'codacy.yml'],
    'codeclimate': ['codeclimate.yml'],
    'codecov': ['codecov.yml'],
    'codegen': ['codegen.config.js'],
    'codekit': ['config.codekit', 'config.codekit2', 'config.codekit3'],
    'codemagic': ['codemagic.yaml'],
    'codeowners': ['codeowners'],
    'coderabbit': ['coderabbit.yaml'],
    'coffeelint': ['coffeelint.json', '.coffeelintignore'],
    'commitizen': ['cz.json', '.czrc'],
    'composer': ['composer.json', 'composer.lock'],
    'conan': ['conanfile.py', 'conanfile.txt'],
    'conda': ['.condarc'],
    'config': ['tool-versions'],
    'context7': ['context7.json'],
    'convex': ['convex.config.js', 'convex.config.ts', 'convex.json'],
    'copilot': ['copilot-instructions.md', 'github-copilot.xml'],
    'coverage': ['coverage', 'lcov.info'],
    'coveralls': ['coveralls.yml'],
    'crowdin': ['crowdin.yml'],
    'csscomb': ['csscomb.json'],
    'csslint': ['.csslintrc'],
    'cursorrules': ['.cursorignore', '.cursorindexingignore', 'cursorrules'],
    'cvs': ['.cvsignore'],
    'cypress': ['cypress.env.json', 'cypress.json'],
    'darcs': ['.boringignore'],
    'dartlang-ignore': ['.pubignore'],
    'databricks': ['databricks.yaml', 'databricks.yml'],
    'datadog': [
      'code-security.datadog.yaml',
      'code-security.datadog.yml',
      'datadog-ci.json',
      'repository.datadog.yaml',
      'repository.datadog.yml',
      'service.datadog.yaml',
      'static-analysis.datadog.yaml',
      'static-analysis.datadog.yml',
    ],
    'dbt': ['dbt_cloud.yml', 'dbt_project.yml', '.dbtignore'],
    'dbt-bouncer': ['dbt-bouncer.toml', 'dbt-bouncer.yaml', 'dbt-bouncer.yml'],
    'debian': ['aptfile'],
    'deepsource': ['.deepsource.toml'],
    'deno': ['deno'],
    'denoify': ['.denoifyrc'],
    'dependabot': ['dependabot.yaml', 'dependabot.yml'],
    'dependencies': ['dependencies.yml'],
    'devcontainer': ['devcontainer.json'],
    'devenv': ['devenv.lock', 'devenv.nix', 'devenv.yaml'],
    'devprune': ['.devprune.json', 'ignore.devprune.json'],
    'direnv': ['.envrc'],
    'docker': ['dockerfile', '.dockerignore'],
    'dockertest': ['docker-compose.test.yml'],
    'docz': ['.doczrc'],
    'dojo': ['.dojorc'],
    'doppler': ['doppler-template.yaml', 'doppler.yaml'],
    'doxyfile': ['doxyfile'],
    'drone': ['drone.yml', 'drone.yml.sig'],
    'dune': ['dune', 'dune-project', 'dune-workspace'],
    'dvc': ['dvc'],
    'earthly': ['earthfile', '.earthlyignore'],
    'eas-metadata': ['store.config.json'],
    'editorconfig': ['.editorconfig'],
    'electron': ['forge.config.js', 'forge.config.ts'],
    'eleventy': [
      'eleventy.config.cjs',
      'eleventy.config.js',
      'eleventy.config.mjs',
      'eleventy.js',
      '.eleventyignore',
    ],
    'elm': ['elm-package.json'],
    'ember': ['ember-cli'],
    'erlang': ['emakefile', 'emakerfile'],
    'eslint': ['eslintcache', '.eslintignore'],
    'expo': ['app.json', 'eas.json'],
    'fantasticon': ['.fantasticonrc', '.fantasticonrc.js', '.fantasticonrc.json'],
    'fastly': ['fastly.toml'],
    'fauna': ['.faunarc'],
    'favicon': ['favicon.ico'],
    'firebase': ['.firebaserc'],
    'firebasehosting': ['firebase.json'],
    'firebasestorage': ['storage.rules'],
    'firestore': ['firestore.indexes.json', 'firestore.rules'],
    'fleet': ['fleet.yaml'],
    'floobits': ['.flooignore'],
    'flow': ['flowconfig'],
    'flutter': ['flutter-plugins', 'flutter-plugins-dependencies', 'metadata'],
    'flutter-package': ['packages', 'pubspec.lock', 'pubspec.yaml'],
    'flyio': ['fly.toml'],
    'fnox': ['fnox.toml', '.fnox.toml', 'fnox.local.toml', '.fnox.local.toml'],
    'fossa': ['.fossaignore'],
    'fossil': ['.ignore-glob'],
    'fresh': ['fresh.config.ts', 'fresh.gen.ts'],
    'frontcommerce': ['front-commerce.config.ts', 'front-commerce.js'],
    'funding': ['funding.yml'],
    'fusebox': ['fuse.js'],
    'gcloud': ['.gcloudignore'],
    'gemini': ['gemini.md'],
    'git': [
      '.git',
      '.git-blame-ignore-revs',
      '.gitattributes',
      '.gitconfig',
      '.gitignore',
      '.gitkeep',
      '.gitmessage',
      '.gitmodules',
      '.issuetracker',
      '.mailmap',
    ],
    'gitlab': ['gitlab-ci.yml'],
    'gleamconfig': ['gleam.toml'],
    'glide': ['glide.yml'],
    'glitter': ['.glitterrc'],
    'go-package': ['go.mod', 'go.sum'],
    'go-work': ['go.work', 'go.work.sum'],
    'graphql': ['gqlconfig'],
    'graphql-config': ['graphqlconfig'],
    'greenkeeper': ['greenkeeper.json'],
    'grok': ['grok.md'],
    'haxe': ['haxelib.json'],
    'haxecheckstyle': ['checkstyle.json'],
    'helix': ['.p4ignore'],
    'helm': ['chart.lock', 'chart.yaml'],
    'heroku': ['heroku.yml'],
    'histoire': ['histoire.config.js', 'histoire.config.ts', 'histoire.js', 'histoire.ts'],
    'horusec': ['horusec-config.json'],
    'htmlhint': ['.htmlhintrc'],
    'htmlvalidate': ['.htmlvalidateignore'],
    'hugo': ['hugo.json', 'hugo.toml', 'hugo.yaml', 'hugo_build.lock'],
    'humanstxt': ['humans.txt'],
    'husky': ['husky.config.js'],
    'imgbot': ['.imgbotconfig'],
    'ionic': ['ionic.config.json', 'ionic.project'],
    'jake': ['jakefile', 'jakefile.js'],
    'jasmine': ['jasmine.json'],
    'jekyll': ['nojekyll'],
    'jest': ['jest.config.babel.js', 'jest.json'],
    'jpm': ['.jpmignore'],
    'jsbeautify': ['jsbeautify', '.jsbeautifyrc'],
    'jsconfig': ['jsconfig.json'],
    'jscpd': ['jscpd.json'],
    'jshint': ['.jshintignore', '.jshintrc'],
    'jsr': ['jsr.json', 'jsr.jsonc'],
    'just': ['justfile'],
    'kitchenci': ['kitchen.yml'],
    'kite': ['.kiteignore'],
    'kodiak': ['.kodiak.toml'],
    'language-configuration': ['language-configuration.json'],
    'layout': ['layout.htm', 'layout.html'],
    'leanconfig': ['lake-manifest.json', 'lakefile.lean', 'lakefile.toml', 'lean-toolchain'],
    'lerna': ['lerna.json'],
    'liara': ['liara.json', '.liaraignore'],
    'licensebat': ['.licrc'],
    'lighthouse': ['budget.json', 'budgets.json'],
    'lime': ['include.xml'],
    'livekit': ['livekit.toml', 'livekit.yaml'],
    'lychee': ['lychee.toml'],
    'madge': ['.madgerc'],
    'mailing': ['mailing.config.json'],
    'makefile': ['makefile'],
    'manifest': ['manifest'],
    'manifest-bak': ['manifest.bak'],
    'manifest-skip': ['manifest.skip'],
    'markdownlint': ['.markdownlintrc'],
    'markdownlint-ignore': ['.markdownlintignore'],
    'maven': ['maven.config'],
    'mcp': ['mcp.json'],
    'mdxlint': ['.mdxlintignore', '.mdxlintrc'],
    'mercurial': ['.hgignore'],
    'meson': ['meson.build'],
    'meteor': ['.meteorignore'],
    'mocha': ['mocha.opts'],
    'modernizr': ['modernizr'],
    'monotone': ['.mtn-ignore'],
    'motif': ['motif.json'],
    'msw': ['mockserviceworker.js'],
    'mypy': ['mypy.ini'],
    'nanostaged': ['.nanostagedrc'],
    'nestjs': ['nest-cli.json', 'nestconfig.json'],
    'netlify': ['netlify.toml'],
    'next': ['next.config.cjs', 'next.config.js', 'next.config.mjs', 'next.config.ts'],
    'nextflow': ['nf'],
    'ng-packagr': ['ng-package.js', 'ng-package.json'],
    'ng-tailwind': ['ng-tailwind.js'],
    'nginx': ['nginx.conf'],
    'ninja': ['build.ninja'],
    'nitro': ['.nitrorc'],
    'nix': ['flake.lock'],
    'node': [
      'node',
      'node-version',
      'node.config.json',
      '.nvmrc',
      'package-lock.json',
      'package.json',
    ],
    'nodemon': ['nodemon.json'],
    'npm': ['npm', 'npm-shrinkwrap.json', '.npmignore', '.npmrc'],
    'npmpackagejsonlint': ['.npmpackagejsonlintignore'],
    'nsri': ['nsri.config.js', '.nsriignore'],
    'nsri-integrity': ['integrity.json'],
    'nuxt': ['nuxtignore', '.nuxtrc'],
    'nx': ['nx.json', '.nxignore'],
    'nyc': ['.nycrc', '.nycrc.json'],
    'objidconfig': ['objidconfig'],
    'ocaml': ['merlin'],
    'ocx': ['ocx.lock', 'ocx.toml'],
    'ohpm': ['.ohpmrc', 'oh-package-lock.json5', 'oh-package.json5'],
    'opencode': ['opencode.json', 'opencode.jsonc'],
    'opentofu': ['opentofu-version'],
    'overmind': ['.overmind.env'],
    'oxc': ['.oxlintignore'],
    'parcel': ['.parcelrc'],
    'pdm': ['pdm-python'],
    'peeky': ['peeky.config.js', 'peeky.config.mjs', 'peeky.config.ts'],
    'phpcsfixer': ['php-cs-fixer.dist.php', 'php-cs-fixer.php', 'php_cs', 'php_cs.dist'],
    'phpunit': ['phpunit', 'phpunit.xml', 'phpunit.xml.dist'],
    'phraseapp': ['phraseapp.yml'],
    'pip': ['pipfile', 'pipfile.lock'],
    'pixi': ['pixi.lock', 'pixi.toml'],
    'platformio': ['platformio.ini'],
    'pnpm': ['pnpm', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'pnpmfile.cjs', 'pnpmfile.js'],
    'precommit': ['pre-commit-config.yaml'],
    'prefect': ['prefect.toml'],
    'prettier': ['.prettierignore'],
    'procfile': ['procfile'],
    'publiccode': ['publiccode.yml'],
    'pug': ['jade-lint.json', '.jade-lintrc', '.pug-lintrc', '.pug-lintrc.js', '.pug-lintrc.json'],
    'purgecss': ['purgecss.config.js'],
    'pyenv': ['python-version'],
    'pypi': ['pyproject.toml'],
    'pyrefly': ['pyrefly.toml'],
    'pytest': ['pytest.ini', 'pytest.toml'],
    'pythonconfig': [
      'conf.py',
      'config.py',
      '.pdbrc',
      '.pdbrc.py',
      'python_history',
      'settings.py',
      'setup.py',
    ],
    'pytyped': ['py.typed'],
    'pyup': ['pyup', 'pyup.yml'],
    'qmldir': ['qmldir'],
    'qrc': ['.qrc'],
    'quartoconfig': ['_quarto.yaml', '_quarto.yml'],
    'quasar': ['quasar.conf.js'],
    'quokka': ['quokka'],
    'railway': ['railway.json', 'railway.toml'],
    'rake': ['rakefile'],
    'readthedocs': ['readthedocs.yaml'],
    'rector': ['rector.php'],
    'rehype': ['.rehypeignore'],
    'remark': ['.remarkignore'],
    'render': ['render.yaml'],
    'renovate': ['.renovaterc', '.renovaterc.json'],
    'replit': ['replit', 'replit.nix'],
    'retext': ['.retextignore'],
    'reuse': ['reuse.toml'],
    'robots': ['robots.txt'],
    'rome': ['rome.json'],
    'rspack': ['rslint.json', 'rslint.jsonc'],
    'rspec': ['rspec'],
    'rubocop': ['rubocop.yml', 'rubocop_todo.yml'],
    'ruby': ['ruby-version'],
    'ruff': ['ruff.toml'],
    'rust-toolchain': ['rust-toolchain', 'rust-toolchain.toml'],
    's-lang': ['.isisrc', '.jedrc', '.slshrc'],
    'sails': ['.sailsrc'],
    'sapphire-framework-cli': ['.sapphirerc', '.sapphirerc.json', 'sapphirerc.yml'],
    'sentry': ['.sentryclirc'],
    'shadcn': ['components.json'],
    'shellcheck': ['.shellcheckrc'],
    'shuttle': ['shuttle.toml'],
    'sitemap': ['sitemap.atom', 'sitemap.rss', 'sitemap.txt', 'sitemap.xml'],
    'skill': ['skill.md'],
    'smithery': ['smithery.yaml'],
    'snapcraft': ['snapcraft.yaml'],
    'snaplet': ['snaplet.config.js', 'snaplet.config.ts'],
    'snyk': ['snyk'],
    'solidarity': ['solidarity', 'solidarity.json'],
    'spin': ['spin.toml'],
    'stackblitz': ['.stackblitzrc'],
    'styleci': ['.styleci.yml'],
    'stylelint': ['stylelintcache', '.stylelintignore'],
    'stylish-haskell': ['stylish-haskell.yaml'],
    'subversion': ['.svnignore'],
    'svelteconfig': ['svelte.config.js', 'svelte.config.ts'],
    'swc': ['.swcrc'],
    'swift': ['package.pins'],
    'symfony': ['symfony.lock'],
    'taplo': ['taplo.toml'],
    'tauri': ['tauri.conf.json', '.taurignore'],
    'testcafe': ['.testcaferc.json'],
    'textlint': ['.textlintignore'],
    'tfs': ['.tfignore'],
    'tiltfile': ['.tiltignore'],
    'tmux': ['tmux.conf'],
    'tombi': ['.tombi.toml', 'tombi.toml'],
    'tox': ['tox.ini'],
    'travis': ['travis.yml'],
    'trivy': ['trivy.yaml', '.trivyignore'],
    'trunk': ['trunk.yaml'],
    'tsdoc': ['tsdoc.json'],
    'tslint': ['tslint.json', 'tslint.yaml', 'tslint.yml'],
    'turbo': ['microfrontends.json', 'microfrontends.jsonc', 'turbo.json', 'turbo.jsonc'],
    'ty': ['ty.toml'],
    'unibeautify': ['unibeautify.config.js'],
    'unlicense': ['unlicence', 'unlicense'],
    'uv': ['uv.lock', 'uv.toml'],
    'vagrant': ['vagrantfile'],
    'vale': ['vale.ini'],
    'vapor': ['vapor.yml'],
    'vercel': ['now.json', '.nowignore', 'vercel.json', '.vercelignore'],
    'vim': ['.gvimrc', '.vimrc'],
    'vlt': ['vlt-lock.json', 'vlt.json'],
    'vscode': ['.vscodeignore'],
    'vueconfig': ['vue.config.cjs', 'vue.config.js', 'vue.config.mjs', '.vuerc'],
    'wally': ['wally.lock', 'wally.toml'],
    'warp': ['warp.md'],
    'watchmanconfig': ['watchmanconfig'],
    'weblate': ['weblate', 'weblate.ini'],
    'wercker': ['wercker.yml'],
    'werf': ['werf-giterminism.yaml', 'werf-includes.yaml', 'werf.yaml'],
    'windi': ['windi.config.js', 'windi.config.ts'],
    'wpml': ['wpml-config.xml'],
    'xo': ['xo-config'],
    'xorg': ['xcompose'],
    'xposed': [
      'java_init.list',
      'native_init',
      'native_init.list',
      'scope.list',
      'module.prop',
      'xposed_init',
    ],
    'yamllint': ['yamllint'],
    'yandex': ['yaspeller.json', '.yaspellerrc'],
    'yarn': [
      'yarn',
      'yarn-integrity',
      'yarn-metadata.json',
      'yarn-state.yml',
      'yarn.lock',
      'yarnclean',
      '.yarnignore',
      '.yarnrc',
      '.yarnrc.yml',
    ],
    'yeoman': ['.yo-rc.json'],
    'zensical': ['zensical.toml'],
    'zizmor': ['zizmor.yaml', 'zizmor.yml'],
    'zsh': ['.zlogin', '.zprofile', '.zshrc', 'zlogin', 'zprofile', 'zshrc'],
  },
  fileExtensions: {
    'access': [
      'accda',
      'accdb',
      'accdc',
      'accde',
      'accdp',
      'accdr',
      'accdt',
      'accdu',
      'ade',
      'adp',
      'laccdb',
      'ldb',
      'mam',
      'maq',
      'mdb',
      'mdw',
    ],
    'actionscript': ['as'],
    'ada': ['ada'],
    'advpl': ['prw'],
    'affinity': ['af', 'aftemplate'],
    'affinitydesigner': ['afdesign', 'affinitydesigner'],
    'affinityphoto': ['affinityphoto', 'afphoto'],
    'affinitypublisher': ['affinitypublisher', 'afpub'],
    'agda': ['agda'],
    'ai': ['ai'],
    'al': ['al'],
    'al-dal': ['dal'],
    'alloy': ['alloy'],
    'ansible': ['ansible'],
    'antlr': ['g4'],
    'anyscript': ['any'],
    'apache': ['htaccess'],
    'apex': ['cls'],
    'apib': ['apib'],
    'apl': ['apl'],
    'applescript': ['applescript'],
    'appscript': ['gs'],
    'arduino': ['ino', 'pde'],
    'asciidoc': ['adoc'],
    'aseprite': ['ase', 'aseprite'],
    'asp': ['asp'],
    'aspx': ['ascx', 'aspx'],
    'assembly': ['asm', 's'],
    'astro': ['astro'],
    'atom': ['atom'],
    'ats': ['ats'],
    'audio': [
      'aac',
      'act',
      'aiff',
      'amr',
      'ape',
      'au',
      'dct',
      'dss',
      'dvf',
      'flac',
      'gsm',
      'iklax',
      'ivs',
      'm4a',
      'm4b',
      'm4p',
      'mmf',
      'mogg',
      'mp3',
      'mpc',
      'msv',
      'oga',
      'ogg',
      'opus',
      'ra',
      'raw',
      'tta',
      'vox',
      'wav',
      'wma',
    ],
    'autohotkey': ['ahk'],
    'autoit': ['au3'],
    'avif': ['avif'],
    'avro': ['avcs'],
    'awk': ['awk'],
    'azure': ['azcli'],
    'azurepipelines': ['azure-pipelines.yml'],
    'azurestreamanalytics': ['asaql'],
    'bak': ['back', 'backup', 'bak'],
    'ballerina': ['bal'],
    'bat': ['bat'],
    'bats': ['bats'],
    'bazel': ['bazel', 'bzl'],
    'befunge': ['bf'],
    'bicep': ['bicep'],
    'biml': ['biml'],
    'binary': [
      'a',
      'app',
      'bin',
      'cma',
      'cmi',
      'cmo',
      'cmx',
      'cmxa',
      'dll',
      'exe',
      'hl',
      'ilk',
      'lib',
      'n',
      'ndll',
      'o',
      'obj',
      'pdb',
      'pyc',
      'pyd',
      'pyo',
      'scpt',
      'scptd',
      'so',
    ],
    'blade': ['blade.php'],
    'blender': ['blend'],
    'blitzbasic': ['bb', 'blitzbasic'],
    'bolt': ['bolt'],
    'bosque': ['bsq'],
    'bruno': ['bru'],
    'buf': ['buf.gen.yaml', 'buf.gen.yml', 'buf.work.yaml', 'buf.work.yml', 'buf.yaml', 'buf.yml'],
    'bun': ['lockb'],
    'bundler': ['gemfile', 'gemfile.lock'],
    'c': ['c'],
    'c-al': ['cal'],
    'c3': ['c3'],
    'cabal': ['cabal'],
    'cairo': ['cairo'],
    'cake': ['cake'],
    'cangjie': ['cj'],
    'capnp': ['capnp'],
    'casc': ['casc'],
    'cddl': ['cddl'],
    'cert': ['cer', 'crl', 'crt', 'csr', 'der', 'p12', 'p7b', 'p7r', 'pfx', 'src', 'sst', 'stl'],
    'ceylon': ['ceylon'],
    'cf': ['cfml', 'lucee'],
    'cfc': ['cfc'],
    'cfm': ['cfm'],
    'cheader': ['h'],
    'chef-cookbook': ['ckbk'],
    'circom': ['circom'],
    'class': ['class'],
    'clojure': ['cjm', 'cljc', 'clojure'],
    'clojurescript': ['cljs', 'clojurescript'],
    'cloudfoundry': ['yml'],
    'cmake': ['cmake'],
    'cobol': ['cbl'],
    'codekit': ['kit'],
    'codeql': ['ql'],
    'coffeescript': ['coffee'],
    'config': ['plist', 'properties'],
    'confluence': ['confluence'],
    'copilot': ['instructions.md'],
    'coverage': ['lcov'],
    'cpp': ['cpp'],
    'cppheader': ['h++', 'hh', 'hpp', 'hxx'],
    'crystal': ['cr'],
    'csharp': ['cs', 'csx'],
    'csproj': ['csproj'],
    'css': ['acss', 'ccss', 'css', 'less', 'mcss', 'nss', 'pcss', 'postcss', 'scss'],
    'cssmap': ['css.map'],
    'csv': ['csv', 'tsv'],
    'cucumber': ['feature'],
    'cuda': ['cu'],
    'cue': ['cue'],
    'cypress-spec': ['cy.cjs', 'cy.coffee', 'cy.js', 'cy.jsx', 'cy.mjs', 'cy.ts', 'cy.tsx'],
    'cython': ['pyx'],
    'dartlang': ['dart'],
    'dartlang-generated': ['freezed.dart', 'g.dart'],
    'db': ['db'],
    'dbml': ['dbml'],
    'debian': ['deb'],
    'delphi': ['pas'],
    'design-tokens': [
      'resolver.json',
      'resolver.json5',
      'resolver.jsonc',
      'tokens.json',
      'tokens.json5',
      'tokens.jsonc',
    ],
    'dhall': ['dhall'],
    'diff': ['diff'],
    'django': ['djt'],
    'dlang': ['d'],
    'docker': ['hcl'],
    'docpad': ['eco'],
    'dotenv': ['env'],
    'doxyfile': ['doxyfile'],
    'doxygen': ['dox'],
    'drawio': ['dio', 'drawio'],
    'drools': ['drl'],
    'dtd': ['dtd'],
    'duckdb': ['duckdb'],
    'dustjs': ['dust'],
    'dylan': ['dylan'],
    'earthly': ['earthfile'],
    'edge': ['edge'],
    'eex': ['eex', 'heex', 'html-heex', 'phoenix-heex'],
    'ejs': ['ejs'],
    'elastic': ['es'],
    'elixir': ['ex'],
    'elm': ['elm'],
    'emacs': ['el', 'elc'],
    'ensime': ['ensime'],
    'eps': ['eps'],
    'epub': ['epub'],
    'erb': ['erb'],
    'erlang': ['erl'],
    'esphome': ['yaml'],
    'excalidraw': ['excalidraw', 'excalidraw.json', 'excalidraw.png', 'excalidraw.svg'],
    'excel': ['xls', 'xlsb', 'xlsm', 'xlsx'],
    'falcon': ['falcon'],
    'fauna': ['fql'],
    'fbx': ['fbx'],
    'fitbit': ['fba'],
    'fla': ['fla'],
    'flash': ['swc', 'swf'],
    'flatbuffers': ['fbs'],
    'flow': ['js.flow'],
    'flowgorithm': ['fprg'],
    'font': ['eot', 'pfa', 'pfb', 'sfd', 'ttf', 'woff', 'woff2'],
    'fortran': ['f'],
    'freemarker': ['ftl'],
    'fritzing': ['fz', 'fzb', 'fzbz', 'fzp', 'fzpz', 'fzz'],
    'fsharp': ['fs'],
    'fsproj': ['fsproj'],
    'fthtml': ['fthtml'],
    'galen': ['gspec'],
    'gamemaker': ['gml', 'gmx'],
    'gamemaker2': ['yy', 'yyp'],
    'gcode': ['gcode'],
    'gdscript': ['gd'],
    'gduid': ['gd.uid'],
    'genstat': ['gen'],
    'geojson': ['geojson'],
    'gimp': ['xcf'],
    'git': ['git'],
    'gleam': ['gleam'],
    'glimmer': ['gjs'],
    'glsl': ['glsl'],
    'gltf': ['glb', 'gltf'],
    'glyphs': ['glyphs'],
    'gnu': ['am', 'ld', 'm4', 'makefile', 'mk'],
    'gnuplot': ['gp'],
    'go': ['go'],
    'go-package': ['mod'],
    'go-work': ['work'],
    'goctl': ['api'],
    'godot': ['godot'],
    'gpg': ['gpg', 'pgp'],
    'gradle': ['gradle', 'gradle.kts'],
    'grain': ['gr'],
    'graphql': ['gql'],
    'graphviz': ['gv'],
    'grit': ['grit'],
    'groovy': ['groovy'],
    'haml': ['haml'],
    'handlebars': ['hbs'],
    'harbour': ['prg'],
    'hashicorp': ['hcl2', 'sentinel'],
    'haskell': ['hs', 'lhs'],
    'haxe': ['haxe'],
    'haxedevelop': ['hxproj'],
    'helm': ['helm.tpl'],
    'hip': ['hip'],
    'hjson': ['hjson'],
    'hlsl': ['hlsl'],
    'host': ['hosts'],
    'html': ['html', 'htm', 'xhtml'],
    'http': ['http'],
    'huff': ['huff'],
    'hunspell': ['aff'],
    'hurl': ['hurl'],
    'hy': ['hy'],
    'hygen': ['ejs.t'],
    'hypr': ['hypr'],
    'icl': ['icl'],
    'idris': ['idr', 'lidr'],
    'idrisbin': ['ibc'],
    'idrispkg': ['ipkg'],
    'image': ['bmp', 'gif', 'heic', 'icns', 'ico', 'jpeg', 'jpg', 'png', 'tiff', 'webp'],
    'imba': ['imba', 'imba2'],
    'inc': ['inc', 'include'],
    'infopath': ['infopathxml', 'xsf', 'xsn', 'xtp2'],
    'informix': ['4gl'],
    'ini': ['ini'],
    'ink': ['ink'],
    'innosetup': ['iss'],
    'io': ['io'],
    'iodine': ['id'],
    'janet': ['janet'],
    'jar': ['jar'],
    'java': ['java'],
    'jbuilder': ['jbuilder'],
    'jekyll': ['jekyll'],
    'jenkins': ['jenkins'],
    'jest-snapshot': ['jest-snap'],
    'jetbrains': ['iml'],
    'jinja': ['jinja'],
    'js': [
      'cjs',
      'es6',
      'jake',
      'js',
      'jsm',
      'jsx',
      'mjs',
      'pac',
      'sjs',
      'ssjs',
      'xsjs',
      'xsjslib',
    ],
    'jsmap': ['cjs.map', 'js.map', 'mjs.map'],
    'json': ['json', 'json-tmlanguage', 'jsonc', 'jsonl', 'ndjson'],
    'json-schema': ['schema.json'],
    'json5': ['json5'],
    'jsonld': ['json-ld', 'jsonld'],
    'jsonnet': ['jsonnet'],
    'jsp': ['jsp'],
    'jss': ['jss'],
    'juice': ['juice'],
    'julia': ['jl'],
    'jupyter': ['ipynb'],
    'k': ['k'],
    'key': ['key', 'pem'],
    'kivy': ['kv'],
    'kos': ['ks'],
    'kotlin': ['kt', 'ktm'],
    'krita': ['kra'],
    'kusto': ['kusto'],
    'language-configuration': ['language-configuration.json'],
    'lark': ['lark'],
    'latino': ['lat'],
    'layout': ['layout.htm', 'layout.html', 'master'],
    'lean': ['lean'],
    'lemon': ['lemon'],
    'lex': ['flex'],
    'libreoffice-base': ['odb', 'otb'],
    'libreoffice-calc': ['fods', 'ods', 'ots'],
    'libreoffice-draw': ['odg', 'otg'],
    'libreoffice-impress': ['odp', 'otp'],
    'libreoffice-math': ['odf', 'otf'],
    'libreoffice-writer': ['odt', 'ott'],
    'license': ['enc', 'lic', 'unlicence', 'unlicense'],
    'lilypond': ['ly'],
    'lime': ['hxp'],
    'liquid': ['liquid'],
    'lisp': ['lisp'],
    'livescript': ['ls'],
    'lnk': ['lnk'],
    'locale': ['strings'],
    'log': ['log', 'tlg'],
    'lolcode': ['lol'],
    'lsl': ['lsl'],
    'lua': ['lua'],
    'luau': ['luau'],
    'lync': ['crec', 'ocrec'],
    'map': ['map'],
    'markdown': ['markdown', 'md', 'mdown', 'mkd'],
    'marko': ['marko'],
    'markojs': ['marko.js'],
    'matlab': [
      'fig',
      'mat',
      'mex',
      'mexn',
      'mexrs6',
      'mn',
      'mum',
      'mx',
      'mx3',
      'rwd',
      'slddc',
      'slx',
      'smv',
      'xvc',
    ],
    'maxscript': ['ms'],
    'maya': ['mel'],
    'mdx': ['mdx'],
    'mediawiki': ['mediawiki'],
    'mermaid': ['mermaid', 'mmd'],
    'metal': ['metal'],
    'minecraft': ['mca', 'mcfunction', 'mcmeta'],
    'mivascript': ['mv'],
    'mjml': ['mjml'],
    'mlang': ['pq'],
    'mojo': ['mojo', '🔥'],
    'mojolicious': ['ep'],
    'mondoo': ['mql.yaml', 'mql.yml'],
    'mongo': ['mongo'],
    'mson': ['mson'],
    'mustache': ['mst', 'mustache'],
    'mvt': ['mvt'],
    'n64': ['n64', 'nrm', 'z64'],
    'ndst': ['ndst.json', 'ndst.yaml', 'ndst.yml'],
    'nearly': ['ne'],
    'neo4j': ['cypher'],
    'nginx': ['nginx'],
    'nim': ['nim'],
    'nimble': ['nimble'],
    'nix': ['nix'],
    'njsproj': ['njsproj'],
    'noc': ['noc'],
    'nsi': ['nsi'],
    'nuget': ['nupkg', 'nuspec', 'psmdcp', 'snupkg'],
    'numpy': ['npy', 'npz'],
    'nunjucks': ['njs', 'nunj', 'nunjucks'],
    'nushell': ['nu'],
    'objectivec': ['m'],
    'objectivecpp': ['mm'],
    'ocaml': ['ml'],
    'ocaml-intf': ['mli'],
    'ogone': ['o3'],
    'onenote': ['one', 'onepkg', 'onetoc', 'onetoc2', 'sig'],
    'opam': ['opam'],
    'opencl': ['cl', 'opencl'],
    'openhab': ['things'],
    'openscad': ['scad'],
    'opentofu': ['tofu', 'tofu.json', 'tofutest.hcl', 'tofutest.json'],
    'org': ['org'],
    'outlook': ['bcmx', 'msg', 'oft', 'otm', 'pst'],
    'ovpn': ['ovpn'],
    'package': ['pkg'],
    'packer': ['pkr.hcl', 'pkr.json', 'pkrtpl.hcl', 'pkrvars.hcl', 'pkrvars.json'],
    'paket': ['paket.references', 'paket.template'],
    'parquet': ['parquet'],
    'patch': ['patch'],
    'pawn': ['p', 'pwn', 'sma'],
    'pcl': ['pcd'],
    'pddl': ['pddl'],
    'pddl-happenings': ['happenings'],
    'pddl-plan': ['plan'],
    'pdf': ['pdf'],
    'perl': ['pl'],
    'perl6': ['pl6'],
    'pgsql': ['pgsql'],
    'photoshop': ['psd'],
    'php': [
      'aw',
      'ctp',
      'module',
      'phar',
      'php',
      'php1',
      'php2',
      'php3',
      'php4',
      'php5',
      'php6',
      'php7',
      'php8',
      'phps',
      'phpsa',
      'phpt',
      'phtml',
    ],
    'pine': ['pine'],
    'pipeline': ['pipeline'],
    'plantuml': ['iuml', 'plantuml', 'pu', 'puml'],
    'platformio': ['dbgasm'],
    'plsql': ['ddl'],
    'plsql-package': ['pck'],
    'plsql-package-body': ['pkb'],
    'plsql-package-header': ['pkh'],
    'plsql-package-spec': ['pks'],
    'poedit': ['mo', 'po'],
    'polyglot': ['dib'],
    'polymer': ['polymer'],
    'poml': ['poml'],
    'pony': ['pony'],
    'postman': ['postman_collection.json', 'postman_environment.json', 'postman_globals.json'],
    'postscript': ['ps'],
    'powerbi': ['pbinb', 'pbix'],
    'powerpoint': [
      'pa',
      'pot',
      'potm',
      'potx',
      'ppa',
      'ppam',
      'pps',
      'ppsm',
      'ppsx',
      'ppt',
      'pptm',
      'pptx',
      'sldm',
      'sldx',
    ],
    'powershell': ['ps1'],
    'powershell-format': ['format.ps1xml'],
    'powershell-psd': ['psd1'],
    'powershell-psm': ['psm1'],
    'powershell-types': ['types.ps1xml'],
    'prisma': ['prisma'],
    'progress': ['w'],
    'prolog': ['pro'],
    'prometheus': ['rules'],
    'proteus': ['dsn', 'pdsprj'],
    'protobuf': ['proto'],
    'publisher': ['pub', 'puz'],
    'pug': ['pug'],
    'puppet': ['pp'],
    'purescript': ['purs'],
    'pyret': ['arr'],
    'pyscript': ['pyscript'],
    'python': ['cpy', 'ipy', 'pxd', 'pxi', 'py', 'pyi', 'pyw', 'rpy'],
    'pythowo': ['pyowo'],
    'q': ['q'],
    'qbs': ['qbs'],
    'qlikview': ['qvd', 'qvs', 'qvw'],
    'qml': ['qml'],
    'qsharp': ['qs'],
    'quarkdown': ['qd'],
    'quarto': ['qmd'],
    'r': ['r'],
    'ra-syntax-tree': ['rast'],
    'racket': ['rkt'],
    'rake': ['rake'],
    'raku': ['raku'],
    'raml': ['raml'],
    'razor': ['cshtml'],
    'reacttemplate': ['rt'],
    'reactts': ['tsx'],
    'reason': ['re'],
    'red': ['red'],
    'registry': ['reg'],
    'rego': ['rego'],
    'rescript': ['res'],
    'rest': ['rst'],
    'rexx': ['rex'],
    'riot': ['tag'],
    'ripple': ['ripple'],
    'rmd': ['rmd'],
    'rnc': ['rnc'],
    'robotframework': ['robot'],
    'ron': ['ron'],
    'rproj': ['rproj'],
    'rss': ['rss'],
    'ruby': [
      'builder',
      'gemspec',
      'prawn',
      'rabl',
      'rb',
      'rbs',
      'rbw',
      'rjs',
      'rsel',
      'ru',
      'rxml',
      'thor',
    ],
    'rust': ['rs'],
    's-lang': ['sl'],
    'safetensors': ['safetensors'],
    'saltstack': ['sls'],
    'san': ['san'],
    'sas': ['sas'],
    'sass': ['sass'],
    'sbt': ['sbt'],
    'scala': ['scala'],
    'scilab': ['sce'],
    'script': ['wsf'],
    'scss': ['scssm'],
    'sdlang': ['sdl'],
    'search-result': ['code-search'],
    'shaderlab': ['shader', 'unity'],
    'shaderslang': ['slang', 'slangh'],
    'shell': ['bash', 'fish', 'ksh', 'sh', 'zsh'],
    'silverstripe': ['ss'],
    'sino': ['sn'],
    'siyuan': ['sy'],
    'sketch': ['sketch'],
    'skipper': ['eskip'],
    'slice': ['ice'],
    'slim': ['slim'],
    'slint': ['slint'],
    'sln': ['sln', 'slnf', 'slnx'],
    'smarty': ['tpl'],
    'snakemake': ['smk'],
    'snort': ['snort'],
    'solidity': ['sol'],
    'spacengine': ['spe'],
    'sparql': ['rq'],
    'sqf': ['sqf'],
    'sql': ['sql'],
    'sqlite': ['db3', 'sqlite', 'sqlite3'],
    'sqlproj': ['sqlproj'],
    'squirrel': ['nut'],
    'sss': ['sss'],
    'stan': ['stan'],
    'stata': ['do', 'dta'],
    'stencil': ['html.stencil', 'stencil'],
    'storyboard': ['storyboard'],
    'stylable': ['st.css'],
    'styled': ['styled'],
    'stylus': ['styl'],
    'sublime': ['sublime-project'],
    'svelte': ['svelte'],
    'svg': ['svg'],
    'swagger': ['swagger'],
    'swift': ['swift'],
    'swig': ['swig'],
    'systemd': ['link'],
    'systemverilog': ['sv'],
    't4tt': ['tt'],
    'tablegen': ['td'],
    'tcl': ['exp', 'tcl'],
    'teal': ['teal'],
    'templ': ['templ'],
    'tera': ['tera'],
    'terraform': ['tf', 'tf.json', 'tfstate', 'tfvars'],
    'test': ['tst'],
    'testplane': [
      'testplane.cjs',
      'testplane.cts',
      'testplane.js',
      'testplane.jsx',
      'testplane.ts',
      'testplane.tsx',
    ],
    'tex': ['bib', 'dtx', 'sty', 'tex', 'texi', 'tikz'],
    'text': ['txt'],
    'textile': ['textile'],
    'thinkscript': ['tosts'],
    'tm': ['tm', 'tm.hcl'],
    'todo': ['todo'],
    'toit': ['toit'],
    'toml': ['toml'],
    'toon': ['toon'],
    'tree': ['tree'],
    'tres': ['tres'],
    'tsbuildinfo': ['tsbuildinfo'],
    'tscn': ['tscn'],
    'tt': ['tt2', 'tt3'],
    'ttcn': ['ttcn3'],
    'tuc': ['tuc'],
    'twig': ['twig'],
    'typescript': ['cts', 'mts', 'ts'],
    'typescriptdef': ['d.cts', 'd.mts', 'd.ts'],
    'typo3': ['typoscript'],
    'uiua': ['ua'],
    'unison': ['u'],
    'uvue': ['uvue'],
    'vala': ['vala'],
    'vanilla-extract': ['css.ts'],
    'vapi': ['vapi'],
    'vash': ['vash'],
    'vb': ['vb'],
    'vbhtml': ['vbhtml'],
    'vbproj': ['vbproj'],
    'vcxproj': ['vcxproj'],
    'velocity': ['vm'],
    'vento': ['vento', 'vto'],
    'verilog': ['v'],
    'vhdl': ['vhdl'],
    'video': [
      '3g2',
      '3gp',
      'amv',
      'asf',
      'avi',
      'divx',
      'f4a',
      'f4b',
      'f4p',
      'f4v',
      'flv',
      'm2v',
      'm4v',
      'mk3d',
      'mkv',
      'mov',
      'mp2',
      'mp4',
      'mpe',
      'mpeg',
      'mpeg2',
      'mpg',
      'mpv',
      'nsv',
      'ogv',
      'qt',
      'rm',
      'rmvb',
      'svi',
      'vob',
      'webm',
      'wmv',
    ],
    'vim': ['vim'],
    'vitest': ['vitest-snap'],
    'volt': ['volt'],
    'vroom': ['vroom'],
    'vscode': ['code-snippets', 'code-workspace'],
    'vsix': ['vsix'],
    'vsixmanifest': ['vsixmanifest'],
    'vue': ['vue', 'vue2', 'vue3', 'vues', 'vuex'],
    'vvvvvv': ['vvvvvv'],
    'vyper': ['vy', 'vyi'],
    'wasm': ['wasm', 'wast', 'wast.js', 'wat', 'witx', 'wsm'],
    'wasp': ['wasp', 'wasp.ts'],
    'wenyan': ['wy'],
    'wesl': ['wesl'],
    'wgsl': ['wgsl'],
    'wikitext': ['wikitext', 'wt'],
    'wolfram': ['wl'],
    'word': ['doc', 'docm', 'docx', 'dot', 'dotm', 'dotx', 'wll'],
    'wurst': ['wurst'],
    'wxml': ['wxml'],
    'wxss': ['wxss'],
    'xaml': ['axaml', 'xaml'],
    'xcode': ['xcodeproj'],
    'xfl': ['xfl'],
    'xib': ['xib'],
    'xliff': ['xlf', 'xliff'],
    'xmake': ['xmake.lua'],
    'xml': ['pex', 'tmlanguage', 'xml'],
    'xorg': ['xcompose'],
    'xquery': ['xquery'],
    'xsl': ['xsl'],
    'yacc': ['bison'],
    'yaml': ['yaml-tmlanguage'],
    'yang': ['yang'],
    'zig': ['zig'],
    'zip': [
      '7z',
      'br',
      'bz',
      'bz2',
      'bzip2',
      'gz',
      'rar',
      'tar',
      'tgz',
      'whl',
      'xz',
      'zip',
      'zipx',
    ],
  },
  folderNames: {
    'alpine': ['alpine'],
    'android': ['android'],
    'angular': ['.angular'],
    'apache': ['apache', 'apache2', 'httpd'],
    'api': ['.api', '.apis', 'api', 'apis'],
    'app': ['.app', 'app', 'application', 'applications', 'apps'],
    'arangodb': ['arango', 'arangodb'],
    'arch': ['arch'],
    'asset': ['.assets', 'assets'],
    'astro': ['.astro'],
    'audio': ['.audio', '.audios', '.sound', '.sounds', 'audio', 'audios', 'sound', 'sounds'],
    'aurelia': ['aurelia_project'],
    'auth': ['auth', 'authentication', 'authorisation', 'authorization'],
    'aws': ['.aws', 'aws'],
    'azure': ['.azure', 'azure'],
    'azurepipelines': ['.azure-pipelines', '.azuredevops', '.vsts', 'azure-pipelines'],
    'binary': ['.bin', 'bin'],
    'bloc': ['bloc', 'blocs'],
    'blueprint': ['.blueprint', '.blueprints', 'blueprint', 'blueprints'],
    'bot': ['.bot', 'bot'],
    'bower': ['bower_components'],
    'buildkite': ['.buildkite'],
    'cake': ['.cake', 'cake'],
    'cargo': ['.cargo', 'cargo', 'crates'],
    'certificate': ['.certificates', 'certificates', 'certs'],
    'changesets': ['.changeset'],
    'chef': ['.chef', 'chef'],
    'circleci': ['.circleci'],
    'claude': ['.claude'],
    'cli': ['cli', 'cmd', 'command', 'commandline', 'commands', 'console'],
    'client': ['client', 'clients'],
    'cloudflare': ['.cloudflare', 'cloudflare'],
    'cmake': ['.cmake', 'cmake'],
    'common': ['common'],
    'component': ['.components', 'component', 'components', 'gui', 'src-ui', 'ui', 'widgets'],
    'composer': ['.composer', 'composer'],
    'config': [
      '.conf',
      '.config',
      '.configs',
      '.configuration',
      '.configurations',
      '.ini',
      '.initializers',
      '.setting',
      '.settings',
      'conf',
      'config',
      'configs',
      'configuration',
      'configurations',
      'ini',
      'initializers',
      'setting',
      'settings',
    ],
    'controller': [
      '.controllers',
      '.handler',
      '.handlers',
      '__controller__',
      '__controllers__',
      '__handler__',
      '__handlers__',
      'controller',
      'controllers',
      'handler',
      'handlers',
    ],
    'coverage': ['coverage'],
    'css': ['_css', 'css'],
    'cubit': ['cubit', 'cubits'],
    'cursor': ['.cursor'],
    'cypress': ['cypress'],
    'dapr': ['.dapr', 'dapr'],
    'dart': ['.dart_tool', 'dart'],
    'databricks': ['.databricks'],
    'datadog': ['.datadog', 'datadog'],
    'db': [
      'data',
      'database',
      'db',
      'repo',
      'repositories',
      'repository',
      'sql',
      'storage',
      'storages',
      'store',
      'stores',
    ],
    'debian': ['deb', 'debian'],
    'dependabot': ['.dependabot'],
    'devcontainer': ['.devcontainer'],
    'devenv': ['.devenv'],
    'dist': [
      '.build',
      '.dist',
      'build',
      'builds',
      'dist',
      'dists',
      'export',
      'exports',
      'out',
      'outs',
      'release',
      'releases',
      'target',
      'targets',
    ],
    'docker': ['.docker', 'docker'],
    'docs': ['doc', 'docs', 'document', 'documents'],
    'e2e': ['e2e'],
    'elasticbeanstalk': ['.ebextensions', '.elasticbeanstalk'],
    'electron': ['electron'],
    'environments': ['environments'],
    'expo': ['.expo', '.expo-shared'],
    'favicon': ['favicon', 'favicons'],
    'fedora': ['fedora'],
    'flow': ['flow', 'flow-typed'],
    'flutter': ['flutter'],
    'fonts': ['fnt', 'font', 'fonts', 'webfonts'],
    'frontcommerce': ['.front-commerce'],
    'gcp': ['.gcp', 'gcp'],
    'gemini': ['.gemini'],
    'gentoo': ['gentoo'],
    'git': ['.git', '.submodules', 'submodules'],
    'github': ['.github'],
    'gitlab': ['.gitlab'],
    'godot': ['.godot', 'godot'],
    'gradle': ['.gradle', 'gradle'],
    'graphql': ['graphql'],
    'grok': ['.grok'],
    'grunt': ['grunt'],
    'gulp': [
      'gulp',
      'gulpfile.babel.coffee',
      'gulpfile.babel.js',
      'gulpfile.babel.ts',
      'gulpfile.coffee',
      'gulpfile.js',
      'gulpfile.ts',
    ],
    'haxelib': ['.haxelib', 'haxe_libraries'],
    'helper': ['.helper', '.helpers', 'helper', 'helpers'],
    'histoire': ['.histoire'],
    'hook': ['.hook', '.hooks', 'hook', 'hooks'],
    'husky': ['.husky'],
    'idea': ['.idea'],
    'images': [
      '.fig',
      '.figs',
      '.img',
      '.imgs',
      'ico',
      'icon',
      'icons',
      'image',
      'images',
      'img',
      'imgs',
      'screenshot',
      'screenshots',
      'svg',
      'texture',
      'textures',
    ],
    'include': [
      '.inc',
      '.incl',
      '.include',
      '.includes',
      '_inc',
      '_incl',
      '_include',
      '_includes',
      'inc',
      'incl',
      'include',
      'includes',
    ],
    'interfaces': ['interface', 'interfaces'],
    'ios': ['ios'],
    'js': ['js'],
    'json': ['json'],
    'junie': ['.junie'],
    'kiro': ['.kiro'],
    'kotlin': ['.kotlin', 'kotlin'],
    'kubernetes': ['.k8s', '.kube', '.kuber', '.kubernetes', 'k8s', 'kube', 'kuber', 'kubernetes'],
    'less': ['_less', 'less'],
    'library': ['.lib', '.libs', '__lib__', '__libs__', 'lib', 'libraries', 'library', 'libs'],
    'linux': ['linux'],
    'locale': [
      '_locale',
      '_locales',
      'g11n',
      'globalization',
      'i18n',
      'internationalization',
      'l10n',
      'lang',
      'language',
      'languages',
      'locale',
      'locales',
      'localization',
    ],
    'log': ['log', 'logs'],
    'macos': ['darwin', 'macos'],
    'mariadb': ['maria', 'mariadb'],
    'maven': ['.mvn'],
    'mediawiki': ['mediawiki'],
    'memcached': ['.memcached', 'memcached'],
    'meteor': ['.meteor'],
    'middleware': ['middleware', 'middlewares'],
    'minecraft': ['.minecraft'],
    'minikube': ['minik8s', 'minikube', 'minikuber'],
    'mjml': ['.mjml', 'mjml'],
    'mobile': ['.mobile', '.mobiles', 'mobile', 'mobiles'],
    'mock': ['.mocks', '__mocks__', 'mocks'],
    'model': ['.entities', '.model', '.models', 'entities', 'model', 'models'],
    'module': ['modules'],
    'mojo': ['mojo'],
    'mongodb': ['mongo', 'mongodb'],
    'mypy': ['.mypy_cache'],
    'mysql': ['mysql', 'mysqldb'],
    'netlify': ['netlify'],
    'next': ['.next'],
    'nginx': ['conf.d', 'nginx'],
    'nix': ['.niv', '.nix', 'niv', 'nix'],
    'node': ['node_modules'],
    'notebooks': ['notebook', 'notebooks'],
    'notification': ['event', 'events', 'notification', 'notifications'],
    'nuget': ['.nuget'],
    'nuxt': ['.nuxt', 'nuxt'],
    'ocx': ['.ocx'],
    'ohpm': ['oh_modules'],
    'package': ['.package', '.packages', 'package', 'packages', 'pkg'],
    'paket': ['.paket'],
    'php': ['php'],
    'platformio': ['.pio', '.pioenvs'],
    'plugin': [
      '.extension',
      '.extensions',
      '.plugin',
      '.plugins',
      'extension',
      'extensions',
      'plugin',
      'plugins',
    ],
    'prisma': ['prisma'],
    'private': ['.private', 'private'],
    'public': ['.public', 'public'],
    'pytest': ['.pytest_cache'],
    'python': ['.venv', '.virtualenv', '__pycache__'],
    'ravendb': ['ravendb'],
    'redhat': ['redhat', 'rhel'],
    'redis': ['redis'],
    'redux': ['redux'],
    'route': ['_route', '_routes', 'route', 'router', 'routers', 'routes'],
    'sass': ['_sass', '_scss', 'sass', 'scss'],
    'schema': ['schema', 'schemas'],
    'script': ['script', 'scripts'],
    'seedkit': ['.seedkit', 'seedkit'],
    'server': ['server'],
    'services': ['service', 'services'],
    'shared': ['.share', '.shared', '__share__', '__shared__', 'share', 'shared'],
    'slackware': ['slackware'],
    'snaplet': ['.snaplet'],
    'spin': ['.spin'],
    'src': ['__src__', 'source', 'sources', 'src'],
    'sso': ['sso'],
    'story': ['.storybook', '__stories__', 'stories', 'story'],
    'style': ['style', 'styles'],
    'supabase': ['supabase'],
    'suse': ['opensuse', 'suse'],
    'svelte': ['.svelte-kit', 'svelte'],
    'swagger': ['swagger'],
    'tauri': ['src-tauri'],
    'telegram': ['.telegram', 'telegram', 'telegramdesktop'],
    'temp': ['.temp', '.tmp', 'temp', 'tmp'],
    'template': ['.template', '.templates', 'template', 'templates'],
    'test': [
      '.spec',
      '.specs',
      '.test',
      '.tests',
      '__test__',
      '__tests__',
      'integration',
      'spec',
      'specs',
      'test',
      'tests',
    ],
    'theme': ['theme', 'themes'],
    'tools': ['.tools', 'tool', 'tooling', 'tools', 'util', 'utilities', 'utils'],
    'travis': ['.travis'],
    'trunk': ['.trunk'],
    'turbo': ['.turbo'],
    'typescript': ['ts', 'typescript'],
    'typings': ['@types', 'types', 'typings'],
    'vagrant': ['.vagrant', 'vagrant'],
    'vercel': ['.vercel'],
    'video': ['.video', '.videos', 'video', 'videos'],
    'view': [
      '_layout',
      '_layouts',
      '_page',
      '_pages',
      '_view',
      '_views',
      'html',
      'layout',
      'layouts',
      'page',
      'pages',
      'view',
      'views',
    ],
    'vitepress': ['.vitepress'],
    'void': ['void'],
    'vs': ['.vs'],
    'vscode': ['.vscode', 'vscode'],
    'vscode-test': ['.vscode-test'],
    'wasm': ['wasm', 'webassembly'],
    'wasp': ['wasp'],
    'webpack': ['.webpack', 'webpack'],
    'windows': ['win32', 'windows'],
    'windsurf': ['.windsurf'],
    'www': ['.web', 'web', 'www', 'wwwroot'],
    'yarn': ['.yarn'],
    'zed': ['.zed'],
  },
  languageIds: {
    'actionscript': ['actionscript'],
    'ada': ['ada'],
    'advpl': ['advpl'],
    'affectscript': ['affectscript'],
    'agda': ['agda', 'lagda-md', 'lagda-rst', 'lagda-tex'],
    'al': ['al'],
    'alloy': ['alloy'],
    'ansible': ['ansible'],
    'antlr': ['antlr'],
    'anyscript': ['anyscript'],
    'apache': ['apacheconf'],
    'apex': ['apex'],
    'apib': ['apiblueprint'],
    'apl': ['apl'],
    'applescript': ['applescript'],
    'asciidoc': ['asciidoc'],
    'asp': ['asp', 'asp (html)'],
    'assembly': ['arm', 'asm', 'asm-intel-x86-generic', 'asm-collection'],
    'astro': ['astro'],
    'ats': ['ats'],
    'autohotkey': ['ahk', 'ahk2'],
    'autoit': ['autoit'],
    'avro': ['avro'],
    'azure': ['azcli'],
    'azurepipelines': ['azure-pipelines'],
    'azurestreamanalytics': ['asaql'],
    'ballerina': ['ballerina'],
    'bat': ['bat'],
    'bats': ['bats'],
    'bazel': ['bazel', 'bazelrc', 'starlark'],
    'befunge': ['befunge', 'befunge98'],
    'bicep': ['bicep'],
    'biml': ['biml'],
    'binary': ['code-text-binary'],
    'biome': ['biome_syntax_tree'],
    'blade': ['blade', 'laravel-blade'],
    'blitzbasic': ['blitzbasic'],
    'bolt': ['bolt'],
    'bosque': ['bosque'],
    'browserslist': ['browserslist'],
    'bruno': ['bruno'],
    'buf': ['buf', 'buf-gen'],
    'bun': ['bun.lockb'],
    'c': ['c'],
    'c-al': ['c-al'],
    'c3': ['c3'],
    'cabal': ['cabal'],
    'caddy': ['caddyfile'],
    'cadence': ['cadence'],
    'cairo': ['cairo'],
    'cangjie': ['Cangjie'],
    'capnp': ['capnp', 'capnproto'],
    'casc': ['casc'],
    'cddl': ['cddl'],
    'ceylon': ['ceylon'],
    'cf': ['cfml', 'lang-cfml'],
    'cfc': ['cfc'],
    'cfm': ['cfmhtml'],
    'chef-cookbook': ['cookbook'],
    'circom': ['circom'],
    'clojure': ['clojure'],
    'clojurescript': ['clojurescript'],
    'cloudfoundry': ['manifest-yaml'],
    'cmake': ['cmake', 'cmake-cache'],
    'cobol': ['cobol'],
    'codeql': ['ql'],
    'coffeescript': ['coffeescript'],
    'config': ['java-properties', 'properties', 'spring-boot-properties'],
    'confluence': ['confluence'],
    'copilot': ['instructions', 'prompt'],
    'cpp': ['cpp'],
    'crystal': ['crystal'],
    'csharp': ['csharp'],
    'css': ['css'],
    'csv': ['csv', 'csv (pipe)', 'csv (semicolon)', 'csv (whitespace)', 'dynamic csv', 'tsv'],
    'cucumber': ['cucumber', 'feature'],
    'cuda': ['cuda', 'cuda-cpp'],
    'cue': ['cue'],
    'cython': ['cython'],
    'dal': ['dal'],
    'dartlang': ['dart'],
    'dbml': ['dbml'],
    'debian': [
      'debian-changelog',
      'debian-control',
      'debian-copyright',
      'debian-upstream-metadata',
    ],
    'delphi': ['pascal', 'objectpascal'],
    'dhall': ['dhall'],
    'diff': ['diff'],
    'django': ['django-html', 'django-txt'],
    'dlang': ['d', 'dscript', 'dml', 'diet'],
    'docker': ['dockerbake', 'dockercompose', 'dockerfile'],
    'dotenv': ['dotenv', 'env'],
    'dotjs': ['dotjs'],
    'doxyfile': ['doxyfile'],
    'doxygen': ['doxygen'],
    'drawio': ['drawio'],
    'drools': ['drools'],
    'dtd': ['dtd'],
    'dustjs': ['dustjs'],
    'dylan': ['dylan', 'dylan-lid'],
    'earthly': ['earthfile'],
    'edge': ['edge'],
    'editorconfig': ['editorconfig'],
    'eex': ['eex', 'html-eex'],
    'ejs': ['ejs'],
    'elastic': ['es'],
    'elixir': ['elixir'],
    'elm': ['elm'],
    'erb': ['erb', 'html.erb'],
    'erlang': ['erlang'],
    'esphome': ['esphome'],
    'excel': ['excel'],
    'falcon': ['falcon'],
    'fauna': ['fql'],
    'flatbuffers': ['flatbuffers'],
    'fortran': [
      'fortran',
      'fortran-modern',
      'FortranFreeForm',
      'FortranFixedForm',
      'fortran_fixed-form',
    ],
    'freemarker': ['ftl'],
    'fsharp': ['fsharp'],
    'fthtml': ['fthtml'],
    'galen': ['galen'],
    'gamemaker': ['gml-gms'],
    'gamemaker2': ['gml-gms2'],
    'gamemaker81': ['gml-gm81'],
    'gcode': ['gcode'],
    'gdscript': ['gdscript'],
    'genstat': ['genstat'],
    'git': ['git-commit', 'git-rebase', 'ignore', 'gitignore'],
    'gleam': ['gleam'],
    'glimmer': ['glimmer-js', 'glimmer-ts'],
    'glsl': ['glsl'],
    'glyphs': ['glyphs'],
    'gnu': ['automake', 'm4', 'makefile', 'makefile2'],
    'gnuplot': ['gnuplot'],
    'go': ['go'],
    'go-package': ['go.mod'],
    'go-work': ['go.work'],
    'goctl': ['goctl'],
    'gradle': ['gradle-kotlin-dsl'],
    'grain': ['grain'],
    'graphql': ['graphql'],
    'graphviz': ['dot'],
    'grit': ['grit'],
    'groovy': ['groovy'],
    'haml': ['haml'],
    'handlebars': ['handlebars'],
    'harbour': ['harbour'],
    'hashicorp': ['hcl'],
    'haskell': ['haskell', 'literate haskell'],
    'haxe': ['haxe', 'hxml', 'Haxe AST dump'],
    'helm': ['helm'],
    'hip': ['hip'],
    'hjson': ['hjson'],
    'hlsl': ['hlsl'],
    'homeassistant': ['home-assistant'],
    'host': ['hosts'],
    'html': ['html'],
    'http': ['http'],
    'huff': ['huff'],
    'hunspell': ['hunspell.aff', 'hunspell.dic'],
    'hurl': ['hurl'],
    'hy': ['hy'],
    'hypr': ['hypr'],
    'icl': ['icl'],
    'imba': ['imba'],
    'informix': ['4GL'],
    'ini': ['ini'],
    'ink': ['ink'],
    'innosetup': ['innosetup'],
    'io': ['io'],
    'iodine': ['iodine'],
    'janet': ['janet'],
    'java': ['java'],
    'jekyll': ['jekyll'],
    'jenkins': ['jenkins', 'declarative', 'jenkinsfile'],
    'jest-snapshot': ['jest-snapshot'],
    'jinja': [
      'jinja',
      'jinja-java',
      'jinja-html',
      'jinja-xml',
      'jinja-css',
      'jinja-json',
      'jinja-md',
      'jinja-py',
      'jinja-rb',
      'jinja-js',
      'jinja-yaml',
      'jinja-toml',
      'jinja-latex',
      'jinja-lua',
      'jinja-properties',
      'jinja-shell',
      'jinja-dockerfile',
      'jinja-sql',
      'jinja-terraform',
      'jinja-nginx',
      'jinja-groovy',
      'jinja-systemd',
      'jinja-cpp',
      'jinja-cisco',
      'jinja-cy',
      'jinja-php',
      'jinja-rust',
    ],
    'js': ['javascript'],
    'json': ['json', 'json-tmlanguage', 'jsonc', 'jsonl'],
    'json5': ['json5'],
    'jsonnet': ['jsonnet'],
    'julia': ['julia', 'juliamarkdown'],
    'just': ['just'],
    'k': ['k'],
    'kivy': ['kivy'],
    'kos': ['kos'],
    'kotlin': ['kotlin', 'kotlinscript'],
    'kusto': ['kusto'],
    'lark': ['lark'],
    'latino': ['latino'],
    'lean': ['lean4', 'lean4markdown'],
    'less': ['less'],
    'lex': ['lex'],
    'lilypond': ['lilypond'],
    'liquid': ['liquid'],
    'lisp': ['lisp', 'autolisp', 'autolispdcl'],
    'locale': ['strings'],
    'log': ['log'],
    'lolcode': ['lolcode'],
    'lsl': ['lsl'],
    'lua': ['lua', 'glua'],
    'markdown': ['chatagent', 'markdown'],
    'marko': ['marko'],
    'matlab': ['matlab'],
    'maxscript': ['maxscript'],
    'maya': ['mel'],
    'mdx': ['mdx'],
    'mediawiki': ['mediawiki'],
    'mermaid': [
      'mermaid',
      'mermaid.architecture',
      'mermaid.block',
      'mermaid.c4Diagram',
      'mermaid.classDiagram',
      'mermaid.erDiagram',
      'mermaid.flowchart',
      'mermaid.gantt',
      'mermaid.gitGraph',
      'mermaid.info',
      'mermaid.journey',
      'mermaid.kanban',
      'mermaid.mindmap',
      'mermaid.packet',
      'mermaid.pie',
      'mermaid.quadrantChart',
      'mermaid.radar',
      'mermaid.requirementDiagram',
      'mermaid.sankey',
      'mermaid.sequenceDiagram',
      'mermaid.stateDiagram',
      'mermaid.timeline',
      'mermaid.xychart',
      'mermaid.zenuml',
    ],
    'meson': ['meson'],
    'metal': ['metal'],
    'minecraft': [
      'bc-mcfunction',
      'bc-minecraft-language',
      'bc-minecraft-molang',
      'bc-minecraft-project',
      'mcdoc',
      'mcfunction',
      'mcmeta',
      'mcscript',
      'minecraft-lang',
      'options-txt',
      'snbt',
    ],
    'mivascript': ['mv'],
    'mjml': ['mjml'],
    'mlang': ['powerquery'],
    'mojo': ['mojo'],
    'mojolicious': ['mojolicious'],
    'mongo': ['mongo'],
    'mson': ['mson'],
    'mustache': ['mustache'],
    'mvt': ['mvt'],
    'mvtcss': ['mvtcss'],
    'mvtjs': ['mvtjs'],
    'nearly': ['nearley'],
    'neo4j': ['cypher'],
    'nginx': ['nginx'],
    'nim': ['nim'],
    'nimble': ['nimble'],
    'nix': ['nix'],
    'nsi': ['nsis', 'nfl', 'nsl', 'bridlensis'],
    'nunjucks': ['nunjucks'],
    'nushell': ['nushell'],
    'objectivec': ['objective-c'],
    'objectivecpp': ['objective-cpp'],
    'ocaml': ['ocaml', 'ocamllex', 'menhir'],
    'ogone': ['ogone'],
    'openhab': ['openhab'],
    'openscad': ['scad'],
    'org': ['org'],
    'packer': ['packer', 'packervars'],
    'pawn': ['pawn'],
    'pddl': ['pddl'],
    'pddl-happenings': ['happenings'],
    'pddl-plan': ['plan'],
    'perl': ['perl'],
    'perl6': ['perl6'],
    'pgsql': ['pgsql', 'postgres'],
    'php': ['php'],
    'pine': ['pine', 'pinescript'],
    'pip': ['pip-requirements'],
    'platformio': [
      'platformio-debug.disassembly',
      'platformio-debug.memoryview',
      'platformio-debug.asm',
    ],
    'plsql': ['plsql', 'oracle', 'oraclesql', 'oracle-sql'],
    'poedit': ['po'],
    'polyglot': ['polyglot-notebook'],
    'polymer': ['polymer'],
    'poml': ['poml'],
    'pony': ['pony'],
    'postcss': ['postcss'],
    'postscript': ['postscript'],
    'powerbi': ['powerbi-desktop', 'powerbi-api'],
    'powershell': ['powershell'],
    'prisma': ['prisma'],
    'processinglang': ['pde'],
    'progress': ['abl'],
    'prolog': ['prolog'],
    'prometheus': ['prometheus'],
    'protobuf': ['proto3', 'proto', 'prototext', 'textproto'],
    'pug': ['jade'],
    'puppet': ['puppet'],
    'purescript': ['purescript'],
    'pyret': ['pyret'],
    'pyscript': ['pyscript'],
    'python': ['python'],
    'pythowo': ['pythowo'],
    'qlikview': ['qlik'],
    'qml': ['qml'],
    'qsharp': ['qsharp'],
    'quarkdown': ['quarkdown'],
    'quarto': ['quarto'],
    'r': ['r'],
    'ra-syntax-tree': ['ra_syntax_tree'],
    'racket': ['racket'],
    'raku': ['raku'],
    'raml': ['raml'],
    'razor': ['razor', 'aspnetcorerazor'],
    'reactjs': ['javascriptreact'],
    'reactts': ['typescriptreact'],
    'reason': ['reason'],
    'red': ['red'],
    'rescript': ['rescript'],
    'rest': ['restructuredtext'],
    'rexx': ['rexx'],
    'riot': ['riot'],
    'ripple': ['ripple'],
    'rmd': ['rmd'],
    'rnc': ['rnc'],
    'robotframework': ['robot'],
    'robots': ['robots-txt'],
    'ruby': ['ruby'],
    'rust': ['rust'],
    's-lang': ['s-lang'],
    'san': ['san'],
    'sas': ['SAS'],
    'sass': ['sass', 'sass.hover'],
    'sbt': ['sbt'],
    'scala': ['scala'],
    'scilab': ['scilab'],
    'script': ['vbscript'],
    'scss': ['scss'],
    'sdlang': ['sdl'],
    'search-result': ['search-result'],
    'shaderlab': ['shaderlab'],
    'shaderslang': ['slang'],
    'shell': ['shellscript'],
    'silverstripe': ['silverstripe'],
    'sino': ['sino'],
    'skill': ['skill'],
    'skipper': ['eskip'],
    'slangacademic': ['slang-academic'],
    'slice': ['slice'],
    'slim': ['slim'],
    'slint': ['slint'],
    'sln': ['sln'],
    'smarty': ['smarty'],
    'snakemake': ['snakemake'],
    'snort': ['snort'],
    'solidity': ['solidity'],
    'sparql': ['sparql'],
    'sqf': ['sqf'],
    'sql': ['sql'],
    'squirrel': ['squirrel'],
    'stan': ['stan'],
    'stata': ['stata'],
    'stencil': ['stencil', 'stencil-html'],
    'stylable': ['stylable'],
    'styled': ['source.css.styled'],
    'stylus': ['stylus'],
    'svelte': ['svelte'],
    'svg': ['svg'],
    'swagger': ['Swagger', 'swagger'],
    'swift': ['swift'],
    'swig': ['swig'],
    'systemd': ['systemd-conf', 'systemd-unit-file'],
    'systemverilog': ['systemverilog'],
    't4tt': ['t4'],
    'tablegen': ['tablegen'],
    'tailwind': ['tailwindcss'],
    'teal': ['teal'],
    'templ': ['templ'],
    'tera': ['tera'],
    'terraform': ['terraform'],
    'tex': ['tex', 'latex', 'bibtex', 'doctex'],
    'text': ['plaintext', 'vim-help'],
    'textile': ['textile'],
    'thinkscript': ['thinkscript'],
    'tiltfile': ['tiltfile'],
    'toit': ['toit'],
    'toml': ['toml'],
    'toon': ['toon'],
    'tt': ['tt'],
    'ttcn': ['ttcn'],
    'tuc': ['tuc'],
    'twig': ['twig'],
    'typescript': ['typescript'],
    'typo3': ['typoscript'],
    'uiua': ['uiua'],
    'unison': ['unison'],
    'vb': ['vb'],
    'vba': ['vba'],
    'velocity': ['velocity'],
    'vento': ['vento'],
    'verilog': ['verilog'],
    'vhdl': ['vhdl'],
    'vim': ['viml', 'vim-snippet'],
    'vitest': ['vitest-snapshot'],
    'vlang': ['v'],
    'volt': ['volt'],
    'vroom': ['vroom'],
    'vscode': ['snippets'],
    'vue': ['vue'],
    'vyper': ['vyper'],
    'wasm': ['wasm', 'wat'],
    'wasp': ['wasp'],
    'wenyan': ['wenyan'],
    'wesl': ['wesl'],
    'wgsl': ['wgsl', 'WGSL'],
    'wikitext': ['wikitext'],
    'wolfram': ['wolfram'],
    'wurst': ['wurstlang', 'wurst'],
    'xmake': ['xmake'],
    'xml': ['xml'],
    'xorg': ['xcompose'],
    'xquery': ['xquery'],
    'xsl': ['xsl', 'xslt'],
    'yacc': ['yacc'],
    'yaml': ['yaml', 'yaml-tmlanguage', 'spring-boot-properties-yaml'],
    'yang': ['yang'],
    'yarn': ['yarnlock'],
    'zig': ['zig'],
    'zip': ['zip'],
  },
}
